### ISSUE TITLE
Mailu on K3S 

### ISSUE THREAD

**Issue by babvin** [Mailu/Mailu#1574] opened 2020-07-23 12:44 UTC
I tried to follow the https://mailu.io/1.7/kubernetes/mailu/index.html for K3S cluster running on Raspberry Pi 4 with Ubuntu 64 Bit. I've converted images to ARM but RSPAMD and Nginx pods are "Crashloopback"ing

Can you please provide a documentation to install on ARM based K8S cluster.

**Comment by Nebukadneza** [comment] 2020-08-17 20:39
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by liquidat** [comment] 2020-08-25 13:48
@babvin This sounds more like an ARM problem than a K3s problem. Sounds like a duplicate of issue #1200 for me. Can you please verify that this is a dup, and if so close this issue and subscribe (and best, contribute 😉 ) if possible there?

**Closed** 2020-08-25 13:52 UTC
