### ISSUE TITLE
Connection refused issue

### ISSUE THREAD

**Issue by CROSP** [Mailu/Mailu#708] opened 2018-11-16 08:44 UTC
Hi, thank you for this project, however I have tried to run it via `docker-compose`, configuration was done in the same way as described on your wiki page.

All containers are booted successfully, ports are bound, albeit I cannot access the web UI - `Connection refused`

Furthermore, you demo page also returns the same error.

What may cause that problem?

**Comment by muhlemmer** [comment] 2018-11-18 16:30
https://github.com/Mailu/Mailu/issues/603#issuecomment-435768784

**Comment by muhlemmer** [comment] 2018-12-05 23:07
@CROSP did you have the same issue like linked comment? Were the dhparam keys finally generated and did the service became available?

**Comment by muhlemmer** [comment] 2018-12-11 21:16
Connection refused usually is caused by two problems:
1. DHparams are still being generated. A fix for this has been back-ported to 1.5 and shouldn't apply to new users.
2. TLS certificate issues.

Both issues can be checked by inspecting the output of `docker-compose logs front`. Please feel free to re-open if you did not find a solution in the logs. In that case please post the logs.

**Closed by muhlemmer** 2018-12-11 21:16 UTC
Labels: status/notabug

**Comment by Salvador1994** [comment] 2019-07-29 15:17
Estou tendo este problema ao tentar me conectar ao imap e smtp

smtp_1       | postfix/smtpd[368]: disconnect from localhost[127.0.0.1] quit=1 commands=1
imap_1       | Jul 29 15:15:03 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>,
