### ISSUE TITLE
Calendar & Contacts still not working

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#334] opened 2017-11-25 16:18 UTC
Tested on both iOS & mac OS

```
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:20 +0000] "PROPFIND /.well-known/carddav HTTP/1.1" 301 178 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:20 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 704 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:20 +0000] "PROPFIND / HTTP/1.1" 301 178 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:20 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 704 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:20 +0000] "PROPFIND /principals/ HTTP/1.1" 301 178 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
front_1      | xxx.xxx.xxx.xxx - - [25/Nov/2017:13:09:21 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 704 "-" "Mac OS X/10.13.2 (17C79a) AddressBook/1808.6"
```

**Comment by kaiyou** [comment] 2017-11-25 16:20
Mmmh, indeed we do not expose a "weel-known" configuration and currently, Webdav and Carddav have to be configured manually. This could be improved I believe.

**Comment by SaiGonSeamus** [comment] 2017-11-25 16:26
I tried it with manual as well on 2 servers, I must be missing a trick, I'll look at again.

**Comment by kaiyou** [comment] 2017-11-25 16:27
You have to set ``https://server/webdav/user@domain.tld/`` as a webdav endpoint. This is not well documented either to be honnest.

**Comment by SaiGonSeamus** [comment] 2017-11-25 16:44
That returned this

`[25/Nov/2017:16:25:23 +0000] "PROPFIND /webdav/admin%40mydomain.com/ HTTP/1.1" 401 188 "-" "Mac+OS+X/10.13.2 (17C79a) CalendarAgent/399.2.2"`

**Comment by kaiyou** [comment] 2017-11-25 18:53
Are you using ``master``, ``1.5.1`` or ``1.5`` (``1.5.1`` will be merge to ``1.5`` tomorrow)

**Comment by SaiGonSeamus** [comment] 2017-11-25 19:04
I'm using Master, I thought 1.5.1 had already been merged. It is in trying to set up credentials that it is failing at if I understand you correctly.

**Comment by aminb** [comment] 2017-11-26 23:23
I have the same issue with Thunderbird and also DAVdroid. I'm on 1.5.1.

**Comment by kaiyou** [comment] 2017-11-27 21:33
Now ``1.5.1`` was merged to ``1.5``. Also, I tested again locally and on a server, and I successfully accessed my Webdav calendar and contacts from evolution and davdroid.

A ``401`` return code is okay if the user is not properly authenticated. My question was, did you setup crendentials in your client? Could you maybe also export logs from ``admin`` and ``webdav`` when the error happens?

**Comment by aminb** [comment] 2017-11-28 03:09
Yeah I'm pretty sure credentials are properly set up. I'm 95% sure about that with Thunderbird, and 100% sure with DAVdroid. Assuming my email is `xx@yy.zz`, I've tried to connect to `/webdav/xx@yy.zz/` with username `xx@yy.zz` and its password with no success. What's interesting is that ics calendars (`/webdav/xx%40yy.zz/personal.ics` in logs below) seem to work fine, but not CalDAV ones (e.g. `/webdav/xx%40yy.zz/school` below)

**Thunderbird:**

`ics` seems to work fine:

```
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:02:43:49 +0000] "GET /webdav/xx%40yy.zz/personal.ics HTTP/1.1" 200 130 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.4.0 Lightning/5.4.4"
```

But I'm having issues with CalDAV:

```
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:02:48:37 +0000] "PROPFIND /webdav/xx%40yy.zz/school/ HTTP/1.1" 404 60 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.4.0 Lightning/5.4.4"
```
The error seems to be a `404` (not found).

---

**DAVdroid:**

DAVdroid's exception trace, among other things, says `InvalidDavResponseException: Expected 207 Multi-Status, got 200 OK`. Would this be a sign that maybe our nginx auth is misconfigured and/or isn't returning the correct status codes?

I also see a whole bunch of `301`'s for DAVdroid's request on server logs:

```
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:02:59:57 +0000] "PROPFIND /xx%40yy.zz/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:02:59:57 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2197 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:03:00:04 +0000] "PROPFIND /xx%40yy.zz/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:03:00:05 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2198 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:03:00:15 +0000] "PROPFIND /xx%40yy.zz/8682c403-0945-48d0-b3f3-13e9756a6118/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:03:00:15 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2200 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
```

**Comment by kaiyou** [comment] 2017-11-28 07:14
I would say you are missing a ``/webdav`` in front of the URL in DAVDroid.
Regarding the 404 however, that I will have to check, it is probably something in Radicale's configuration. I will try and reproduce it tonight.

**Comment by aminb** [comment] 2017-11-28 13:50
Strangely enough, I *did* put `/webdav` in for DAVdroid as well!

Here's some more logs:

```
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:02 +0000] "PROPFIND /webdav/xx@yy.zz/ HTTP/1.1" 207 298 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:02 +0000] "OPTIONS /xx%40yy.zz/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:02 +0000] "PROPFIND /.well-known/carddav HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:02 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:03 +0000] "PROPFIND /.well-known/carddav HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:03 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:03 +0000] "PROPFIND / HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:03 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:04 +0000] "PROPFIND /webdav/xx@yy.zz/ HTTP/1.1" 207 399 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:04 +0000] "OPTIONS /xx%40yy.zz/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND / HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:05 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2201 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:09 +0000] "PROPFIND // HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:09 +0000] "PROPFIND /xx%40yy.zz/ HTTP/1.1" 301 178 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:09 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2203 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
front_1      | xxx.xxx.xxx.xxx - xx@yy.zz [28/Nov/2017:13:42:09 +0000] "PROPFIND /webmail/ HTTP/1.1" 200 2204 "-" "DAVdroid/1.9.1-ose (2017/10/31; dav4android; okhttp3) Android/7.1.2"
```

So DAVdroid does seem to try and look for a `/.well-known/caldav` and `/.well-known/carddav`, which we don't seem to have ?

Thanks for looking into this.

**Comment by kaiyou** [comment] 2017-12-01 09:03
It seems to work properly with Davdroid and clients that support creating collections. Unfortunately, it still does not work properly with Thunderbird for instance.

One could of course create a calendar from another client then export the URL from that client (Davdroid does not seem to support it tough) and insert it in Thunderbird/Outlook/any other client not supporting collection creation.

A pull request was created for Radicale in order to handle creating default new collections for users: https://github.com/Kozea/Radicale/pull/467. Unfortunately, it was dismissed in favor of the new Radicale Web interface, where users can indeed create collections and get the URI for that collection.

Now, exposing yet another web interface to non-power-users sounds like an anti-feature that will just get everyone lost in a mail server distribution that was initially meant to be simple. Still thinking about the proper way to go.

**Comment by aminb** [comment] 2017-12-01 14:04
Thanks for the investigation.

I agree that the situation is not ideal. But if their web interface is decent, I wouldn't be too opposed to it; especially if it isn't huge and bloated. It seems fairly ok: https://github.com/Kozea/Radicale/blob/master/radicale/web.py

**Comment by gregf** [comment] 2017-12-01 18:23
Personally, I would like to see some kind of web interface, I'm having trouble creating calendars right now for use with khal & vdirsyncer.

**Comment by kaiyou** [comment] 2017-12-03 11:27
I guess we can give it a go. I'll how authentication is performed.

**Comment by oz123** [comment] 2018-01-22 22:32
I have managed to get authenticated properly, but I can't use caldav with any client to add calenderas.

**Comment by kaiyou** [comment] 2018-01-24 17:56
@oz123 could you specify which clients you are testing with and what errors are returned by the client?

**Closed** 2019-06-27 06:15 UTC
Labels: type/enhancement
