### ISSUE TITLE
per-account storage quota can't be updated in the UI

### ISSUE THREAD

**Issue by patzm** [Mailu/Mailu#2418] opened 2022-08-16 13:25 UTC
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
🐳 containers:
```
e8ce6905b9bf	mailu/roundcube:1.9.32	Up 2 weeks (healthy)	mailu_webmail_1
45f531f83017	mailu/postfix:1.9.32	Up 2 weeks (healthy)	mailu_smtp_1
4a2ba8505ca6	mailu/dovecot:1.9.32	Up 2 weeks (healthy)	mailu_imap_1
759496f26b60	mailu/rspamd:1.9.32	Up 2 weeks (healthy)	mailu_antispam_1
6ecdb7a2923a	mailu/admin:1.9.32	Up 2 weeks (healthy)	mailu_admin_1
a959a055d648	mailu/nginx:1.9.32	Up 2 weeks (healthy)	mailu_front_1
35a949d45308	redis:alpine	Up 2 weeks	mailu_redis_1
3764fc8a010a	mailu/traefik-certdumper:1.9.32	Up 2 weeks	mailu_certdumper_1
```
🐳 compose:
```
MAILU_VERSION=1.9.32
```
in-code: https://github.com/patzm/dockerfiles/blob/7cfd406d1365228d51750ed3855d7bcd82659631/mailu/.env#L11

## Description
I configured my mail _domain_ with upper limit of 50 GB.
![domain](https://user-images.githubusercontent.com/5219726/184889743-fd5043d5-a2bd-4140-8b11-1482dca3ad0a.png)

I then want to increase the per-user quota from 15 GB (previous limit) to now 50 GB using the slider. Sadly, this never seems to come into effect.
![accounts](https://user-images.githubusercontent.com/5219726/184889585-6667ca96-4878-4349-a979-87a21f6f0806.png)

## Replication Steps
1. Create a new domain with e.g. 15 GB of quota.
2. create at least one account
3. increase the domain quota (btw. I also tested decreasing the quota without effect)
4. try to increase the quota of the account created earlier
5. observe that it gets reset whenever switching back to the account view (see screenshot above).

## Expected behaviour
I would expect the quota to be adjustable.

## Logs
[logs.txt](https://github.com/Mailu/Mailu/files/9351392/logs.txt)
excerpt: 
```
[36madmin_1       |[0m [2022-07-18 23:11:56,755] WARNING in nginx: Invalid user 'foo@bar.baz': (sqlite3.OperationalError) database is locked
[36madmin_1       |[0m [2022-07-18 23:12:02,289] ERROR in app: Exception on /internal/dovecot/quota/storage/foo@bar.baz [POST]
[36madmin_1       |[0m Traceback (most recent call last):
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
[36madmin_1       |[0m     self.dialect.do_execute(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
[36madmin_1       |[0m     cursor.execute(statement, parameters)
[36madmin_1       |[0m sqlite3.OperationalError: database is locked
[36madmin_1       |[0m 
[36madmin_1       |[0m The above exception was the direct cause of the following exception:
[36madmin_1       |[0m 
[36madmin_1       |[0m Traceback (most recent call last):
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
[36madmin_1       |[0m     response = self.full_dispatch_request()
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
[36madmin_1       |[0m     rv = self.handle_user_exception(e)
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
[36madmin_1       |[0m     rv = self.dispatch_request()
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
[36madmin_1       |[0m     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[36madmin_1       |[0m   File "/app/mailu/internal/views/dovecot.py", line 35, in dovecot_quota
[36madmin_1       |[0m     user = models.User.query.get(user_email) or flask.abort(404)
[36madmin_1       |[0m   File "<string>", line 2, in get
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
[36madmin_1       |[0m     return fn(*args, **kwargs)
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 943, in get
[36madmin_1       |[0m     return self._get_impl(ident, loading.load_on_pk_identity)
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl
[36madmin_1       |[0m     return self.session._get_impl(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2869, in _get_impl
[36madmin_1       |[0m     return db_load_fn(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 524, in load_on_pk_identity
[36madmin_1       |[0m     session.execute(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
[36madmin_1       |[0m     result = conn._execute_20(statement, params or {}, execution_options)
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
[36madmin_1       |[0m     return meth(self, args_10style, kwargs_10style, execution_options)
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
[36madmin_1       |[0m     return connection._execute_clauseelement(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
[36madmin_1       |[0m     ret = self._execute_context(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
[36madmin_1       |[0m     self._handle_dbapi_exception(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
[36madmin_1       |[0m     util.raise_(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
[36madmin_1       |[0m     raise exception
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
[36madmin_1       |[0m     self.dialect.do_execute(
[36madmin_1       |[0m   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
[36madmin_1       |[0m     cursor.execute(statement, parameters)
[36madmin_1       |[0m sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[36madmin_1       |[0m [SQL: SELECT user.email AS user_email, user.created_at AS user_created_at, user.updated_at AS user_updated_at, user.comment AS user_comment, user.localpart AS user_localpart, user.password AS user_password, user.quota_bytes AS user_quota_bytes, user.quota_bytes_used AS user_quota_bytes_used, user.global_admin AS user_global_admin, user.enabled AS user_enabled, user.enable_imap AS user_enable_imap, user.enable_pop AS user_enable_pop, user.forward_enabled AS user_forward_enabled, user.forward_destination AS user_forward_destination, user.forward_keep AS user_forward_keep, user.reply_enabled AS user_reply_enabled, user.reply_subject AS user_reply_subject, user.reply_body AS user_reply_body, user.reply_startdate AS user_reply_startdate, user.reply_enddate AS user_reply_enddate, user.displayed_name AS user_displayed_name, user.spam_enabled AS user_spam_enabled, user.spam_threshold AS user_spam_threshold, user.domain_name AS user_domain_name 
[36madmin_1       |[0m FROM user 
[36madmin_1       |[0m WHERE user.email = ?]
[36madmin_1       |[0m [parameters: ('foo@bar.baz',)]
[36madmin_1       |[0m (Background on this error at: https://sqlalche.me/e/14/e3q8)
```
So it seems my database is locked 🔒.

Any idea why this might have happened? And how to unlock it?
Is it related to #2296?

**Comment by frankenstein91** [comment] 2023-01-07 17:10
in my case only the calculation of the quota is not correct. 
slider and list view do not show the same value, but are changing

**Comment by nextgens** [comment] 2023-02-05 13:32
@frankenstein91 we've got a fix for that in #2649 

That isn't the issue reported though. Personally I can't reproduce the "database is locked" problem.

@patzm do you have any other process accessing the sqlite database directly (cronjob, backup script, ...)?

**Comment by patzm** [comment] 2023-02-05 22:00
@nextgens, I only run an `rsync` command that _reads_ the host-mounted directories. You can refer to the [`docker-compose` file](https://github.com/patzm/dockerfiles/blob/954239478cda4075f19f25e7023a198f33fa6c8e/mailu/docker-compose.yml) for the mounts of each respective container.
Otherwise no, not that I am aware of.

Also, I can update that _sometimes_ quota increases work. Now, I have 30 GB. In the https://github.com/Mailu/Mailu/issues/2418#issue-1340355001, you can see it was still 15 GB.

I also just tried setting it to 35 GB. Now, the Web UI shows 32 GB. Weird 😕.

**Comment by patzm** [comment] 2023-02-05 22:38
I have just upgraded to [`v1.9.46`](https://github.com/Mailu/Mailu/releases/tag/1.9.46) and it seems to work better. Without changing anything, it showed the previously set 35 GB now.

**Comment by nextgens** [comment] 2023-02-06 08:07
@patzm the quota fix is in ``1.9.47``. Please re-open this issue if you can reproduce it running at least that version

**Comment by patzm** [comment] 2023-02-06 08:22
I just upgraded. First observation: too many zeros 😅 
![image](https://user-images.githubusercontent.com/5219726/216920269-fc350b88-f81a-4dfa-aa55-ffb2723b522b.png)
However, the admin UI then shows the correct updated value of in this case 44 GB.
Sadly, when logging in as a user and hovering over the fill indicator, I get this:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5219726/216920532-71617c83-65e5-44d2-af65-b2926e5d6688.png">
In a previous version, this mismatch between the admin UI and user UI was also the case.

PS: I can't reopen.

**Comment by ghostwheel42** [comment] 2023-02-06 08:44
Did you restart all containers? and maybe use shift+reload to reload all javascript involved?
This could get rid of the zeroes.

The difference between Mailu and roundcube is because roundcube shows GiB (2^30) while Mailu shows GB (10^9).

**Comment by nextgens** [comment] 2023-02-06 08:46
If we touch this again, I suggest we set ``$config['quota_zero_as_unlimited'] = true;`` in roundcube's config too.

**Comment by patzm** [comment] 2023-02-06 09:03
GiB vs GB difference makes a lot of sense. Thanks.

Yes, I just force-refreshed _and_ also cleared all cookies 🍪. Same result. Maybe we can actually close this issue, because I _can_ update the quota. What's off are two different things:
* the trailing `0`s (new) -> new issue?
* maybe: misleading the user (admin) to think that the quota isn't properly reflected in a Mail front-end. But this is highly arguable.

**Comment by nextgens** [comment] 2023-02-07 09:37
@patzm please retry with ``v1.9.48``

ghostwheel42 has kindly provided a patch fixing the bug I have introduced backporting his code.

**Closed by nextgens** 2023-02-07 09:37 UTC
Labels: type/bug

**Comment by patzm** [comment] 2023-02-07 16:27
nice, that solved it. Thanks @ghostwheel42 🙇 and @nextgens for the ping.
![image](https://user-images.githubusercontent.com/5219726/217303899-e289a542-452d-4bba-b38c-e389b61179fb.png)
