### ISSUE TITLE
No description update for aliase possible using mailu webadmin

### ISSUE THREAD

**Issue by jukey** [Mailu/Mailu#161] opened 2017-02-13 09:05 UTC
## Steps to reproduce the problem

1. Login and select 'E-Mail-Domains' in the main navigation
2. Select the alias symbol for an existing emailaccount.
3. Create an alias called 'foo' without description. Save.
4. Got to the list of aliases again. Select edit for the alias 'foo'.
5. Add a description in the 'Kommentar' (english: comment?) input field.
6. Select 'Erstellen' (English: create?) in order to store changes.

### Expected behaviour

Apart from the fact that the button should be called 'Speichern' (English: 'Save' or 'Update') the comment/description should be stored for this alias.

### Current behaviour

No update happens. Instead an error message is shown next to the 'Alias' input field saying: 'Dieses Feld wird benötigt.'. (English: Mandatory input field?).

**Comment by jukey** [comment] 2017-02-13 14:22
I now see the same happens when I try to add a comment to an email account in the edit email dialogue.

**Comment by kaiyou** [comment] 2017-02-14 20:04
Thank you for the great report. I will try and fix this tonight.

**Comment by kaiyou** [comment] 2017-02-14 20:10
I cannot reproduce the same behaviour, could provide details about your Mailu version and browser configuration?

**Comment by sanduhrs** [comment] 2017-02-14 20:32
Just tried to reproduce on a setup version 1.4
Can't reproduce in latest Firefox on Linux.

**Comment by jukey** [comment] 2017-02-14 22:53
Thanks for the quick response. I am running mailu 1.4.

I am able to reproduce the issue using either latest Firefox or Chromium on Ubuntu 16.4:

- 55.0.2883.87 (Entwickler-Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit) and
-  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

This screenshot was created while creating an alias:

![Create](http://ju-key.de/mailu-alias-create.png)

This screenshot was created while not being able to edit an alias:

![edit](http://ju-key.de/mailu-alias-edit.png)

Please let me know if you need more details.

**Comment by trueserve** [comment] 2017-02-15 05:33
A similar bug existed before, but was fixed.... are you sure you are on version 1.4?

I tried to reproduce this bug on my 1.4 installation, and other than the "Create" mislabeling, I can't recreate the "This field is required." bug.

**Comment by jukey** [comment] 2017-02-15 07:33
You are right, I thought to be on 1.4 but used the master branch which isn't the latest.

Is there any way to see in the admin panel the version of mailu?

So I will do the update and confirm whether the bug disappeared or not.

**Comment by trueserve** [comment] 2017-02-15 08:04
The master branch should be beyond 1.4, but master in docker didn't seem to be the same thing as master here. If you used docker-compose as the instructions show, then try setting the version to 1.4 or latest then re-updating.

The admin panel currently doesn't show a version. It would be nice if it showed the version and git commit hash. Maybe this can be added before the panel is fleshed out more (something I might eventually work on).

**Comment by jukey** [comment] 2017-02-15 21:19
I updated now and it works fine. The only little thing is that the button label is "create" instead if "edit" or "update".

**Comment by kaiyou** [comment] 2017-02-17 17:48
Closing here. I'll change the button to something more generic like "Save". Thank you!

**Closed by kaiyou** 2017-02-17 17:48 UTC
Labels: bug
