### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by differs** [Mailu/Mailu#960] opened 2019-03-05 14:45 UTC
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
@ https://setup.mailu.io/master/submit

**Comment by ionutfilip** [comment] 2019-03-06 12:42
Duplicate of #924. This will be solved after PR #951 will be merged.

**Closed by ionutfilip** 2019-03-06 12:42 UTC
