### ISSUE TITLE
master version postgresql database roundcube webmail 502 Bad Gateway

### ISSUE THREAD

**Issue by qy117121** [Mailu/Mailu#1648] opened 2020-09-30 12:29 UTC
setup.mailu.io  Version master 

Both postgresql and mysql  are 502 Bad Gateway

sqllite can open roundcube webmail

Ranloop can work normally

**Comment by HorayNarea** [comment] 2020-10-02 11:43
I can confirm. The problem is here: https://github.com/Mailu/Mailu/blob/master/webmails/roundcube/start.py#L13-L28

We use the same `DB_HOST` and `DB_FLAVOR` as set by https://setup.mailu.io in `mailu.env` but don't also use `DB_USER`, `DB_PW` and `DB_NAME` …

---

We are very sorry for the inconvenience, and will implement a fix for this, in the meantime as a workaround you can:

a) set `ROUNDCUBE_DB_USER`, `ROUNDCUBE_DB_PW` and `ROUNDCUBE_DB_NAME` in your `mailu.env` to the same as the corresponding variables without `ROUNDCUBE_` – roundcube will then use your external DB with the correct credentials

or

b) set `ROUNDCUBE_DB_FLAVOR=sqlite` – roundcube will then use a separate sqlite file in `$YOUR_MAILU_TOPDIR/webmail/roundcube.db`

**Comment by HorayNarea** [comment] 2020-10-02 11:53
Related issue: #1471

**Comment by qy117121** [comment] 2020-10-02 11:56
I have changed to sqlite, thanks

**Comment by Nebukadneza** [comment] 2020-10-12 20:21
Hi,

I’m wondering what the right thing to do here is. Assuming the user has a external database, our docs instruct the user to create a `mailu` user and `mailu` database. Roundcube is currently geared to want its own database. So either, we leave the user with the duty to create another database, with permissions to the same `mailu` user, or we include the `ROUNDCUBE_DB_` variables in setup, expose and document them.

The third option is to let roundcubes database-init script shove its data into the `mailu` database … which would probably work, but is never guaranteed to not-clash some day in the future, so for me this is the least favorable option.

Is there another way I overlooked?

Also, while i recognize this is a problematic issue, given how much others are around, are we sure this is our last 1.8-rc blocker :sweat_smile: :sweat_drops:  or would we rather also postpone it, like so many other issues … I mean, at least there’s a workaround nicely described thanks to @HorayNarea?

**Closed** 2021-06-29 12:14 UTC
Labels: priority/p0, type/bug
