### ISSUE TITLE
Reverse proxy example for /admin doesn't work properly

### ISSUE THREAD

**Issue by aminb** [Mailu/Mailu#97] opened 2016-11-01 14:03 UTC
Upon trying the [example](https://github.com/Mailu/Mailu/wiki/Use-your-own-reverse-proxy#have-mailu-web-frontend-listen-locally) on wiki, I got a lot of redirections to `http://localhost/`.

Something more elaborate along these lines works however:

```
        location /admin {
                proxy_pass https://localhost:8443/admin;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Script-Name /admin;
        }
```

**Comment by kaiyou** [comment] 2016-11-01 14:13
Indeed, could you try with the following configuration? I do not believe that ``X-Script-Name`` is mandatory in this case. Also, I will modify the ``proxy_pass`` directives.

```
proxy_set_header Host $http_host;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Host $host;
```

**Comment by aminb** [comment] 2016-11-01 14:32
With the above, nginx fails to restart with this error:
```
nginx: [emerg] unknown "proxy_connection" variable
```

And removing that line, nginx still fails, with a similar error:

```
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
```

Without the two lines, nginx restarts of course, but everything is 404.

**Comment by kaiyou** [comment] 2016-11-01 14:36
Okay, I will need to setup an nginx locally, probably tonight then.

**Comment by RaymondSchnyder** [comment] 2016-11-05 21:59
I would like to add the following information:
`   location /admin {
                proxy_pass https://localhost:8443/admin;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Script-Name /admin;
        }`
This works perfectly, but when im adding this for the "/webmail", im getting an 502 Bad Gateway after a looong waiting time with roundcube, and with rainloop, it doesnt show me an error at all (it just loads for hours)

**Comment by aminb** [comment] 2016-11-05 22:08
@RaymondSchnyder You don't need a sophisticated location block for `/webmail`, only for `/admin`.

For `/webmail`, the example in the wiki should suffice:

```
  location /webmail {
    proxy_pass https://localhost:8443/webmail;
  }
```

**Comment by RaymondSchnyder** [comment] 2016-11-05 22:43
@aminb Doesnt work. This redirects me to "https://localhost/webmail" in my browser.

**Comment by aminb** [comment] 2016-11-05 23:55
@RaymondSchnyder Can you paste the rest of your configuration here? The `/admin` configuration I posted at the very top + the `/webmail` I just posted is what I use and they work just fine.

**Comment by RaymondSchnyder** [comment] 2016-11-06 09:58
This is my nginx mail server block, which im using now:
http://pastebin.com/EpTqr8g4

**Comment by aminb** [comment] 2016-11-06 13:43
@RaymondSchnyder Looks pretty much identical to mine, except my `location /` block:

```
location / {
                return 302 $scheme://$host/webmail/;
        }
```

But that shouldn't be relevant to your redirection error. Let's wait for @kaiyou to chime in.

**Comment by kaiyou** [comment] 2016-11-06 14:56
I fear the 302 is problematic indeed. First it is missing a port, which will fail if no nginx is listening on 443, plus it makes no sense once behind a first reverse proxy. I am preparing a working configuration for the front nginx.

**Comment by kaiyou** [comment] 2016-11-06 15:32
Okay, after some digging, most of the issue is related to 302 and 301 replies.

Because not all components are ready for redirections based on headers, some will work, some won't.
One simple solution would be adding this to your ``proxy_pass`` : 

```
proxy_redirect https://localhost https://your-domain.com;
```

**Comment by RaymondSchnyder** [comment] 2016-11-07 10:16
@kaiyou This fixxed the issue! Is this a Workaround or a final solution for this?

Let me know if I can help or providing more Information.

Greetings and very thankfully

Raymond

**Comment by kaiyou** [comment] 2016-11-07 10:21
It is the simplest and cleanest way of doing it as I see it for now. I will add a reference in the Wiki.

**Comment by RaymondSchnyder** [comment] 2016-11-09 06:25
Can i close the issue as its resolved or should it stay open?

**Closed** 2016-11-09 08:35 UTC
Labels: question

**Comment by oz123** [comment] 2018-01-21 16:25
This still an issue for me. The examples in the documentation don't work, and the pastebin linked here is no longer available.

**Comment by kaiyou** [comment] 2018-01-24 18:06
It's become another issue due to documentation about reverse proxy being behind the actual configuration. Could you open another issue to explain about your setup and the error messages you get?
