### ISSUE TITLE
[helm] SASL login name rejected: Server configuration error 

### ISSUE THREAD

**Issue by 0gp** [Mailu/Mailu#2386] opened 2022-07-08 09:03 UTC
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists. (#2359)
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] kubernetes

### Versions
```
1.9.26
```

## Description
I've deployed Mailu with Helm, DNS were configured, keys were generated and set up. it worked fine for over 2 day.
Since today I can't send mails.

## Replication Steps
deploy using helm

## Expected behaviour
sendig e-mails should be successfull

## Logs
```
2022-07-08T08:50:44.033783+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/smtpd[63828]: lost connection after RCPT from 178.115.32.249.wireless.dyn.drei.com[178.115.32.249]
Fri, Jul 8 2022 10:50:44 am | 2022-07-08T08:50:44.034047+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/smtpd[63828]: disconnect from 178.115.32.249.wireless.dyn.drei.com[178.115.32.249] ehlo=2 xclient=0/1 mail=1 rcpt=0/1 commands=3/5
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.240891+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/smtpd[63603]: connect from 10-42-3-130.mailu-front.mailu-mailserver.svc.cluster.local[10.42.3.130]
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.246024+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: connect to /tmp/podop.socket: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.246037+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: table socketmap:unix:/tmp/podop.socket:domain lookup error: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.246045+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains: socketmap:unix:/tmp/podop.socket:domain: table lookup problem
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.246054+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains lookup failure
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247056+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: connect to /tmp/podop.socket: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247065+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: table socketmap:unix:/tmp/podop.socket:domain lookup error: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247071+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains: socketmap:unix:/tmp/podop.socket:domain: table lookup problem
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247076+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains lookup failure
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247315+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: connect to /tmp/podop.socket: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247328+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: table socketmap:unix:/tmp/podop.socket:domain lookup error: No such file or directory
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247335+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains: socketmap:unix:/tmp/podop.socket:domain: table lookup problem
Fri, Jul 8 2022 10:51:48 am | 2022-07-08T08:51:48.247340+00:00 mailu-postfix-6846ff6f7d-78gz5 postfix/trivial-rewrite[63640]: warning: virtual_mailbox_domains lookup failure
```

**Comment by fascinatedcow** [comment] 2022-07-08 11:56
I've also seen this issue, but it seems only to occur when my cluster doesn't have much spare cpu or my storage is busy. The only way I could fix it was by scaling down everything in the namespace and scaling it back up again. Bouncing individual pods doesn't fix it.

**Comment by nextgens** [comment] 2022-07-08 12:40
This is a duplicate of #2359.

Again, bugs related to helm charts should be reported on https://github.com/Mailu/helm-charts/

**Closed by nextgens** 2022-07-08 12:40 UTC
