### ISSUE TITLE
Closing open relay

### ISSUE THREAD

**Issue by bolet** [Mailu/Mailu#1560] opened 2020-07-03 12:32 UTC
The default setup leaves mailu an open relay for spammers to use. Bad!

I had to make the following changes to main.cf and master.cf (inside the postfix container). Please feel free to include my changes if you encounter the same misbehaviour. 

```diff
diff --git a/core/postfix/conf/main.cf b/core/postfix/conf/main.cf
index 43ed2df..1e6ac72 100644
--- a/core/postfix/conf/main.cf
+++ b/core/postfix/conf/main.cf
@@ -17,7 +17,8 @@ queue_directory = /queue
 message_size_limit = {{ MESSAGE_SIZE_LIMIT }}

 # Relayed networks
-mynetworks = 127.0.0.1/32 [::1]/128 {{ SUBNET }} {{ RELAYNETS }}
+mynetworks = 127.0.0.1/32 [::1]/128

 # Empty alias list to override the configuration variable and disable NIS
 alias_maps =
@@ -100,10 +101,12 @@ smtpd_helo_required = yes

 smtpd_client_restrictions =
   permit_mynetworks,
+  permit_sasl_authenticated,
   check_sender_access ${podop}senderaccess,
   reject_non_fqdn_sender,
   reject_unknown_sender_domain,
   reject_unknown_recipient_domain,
+  reject_unauth_destination,
   permit

 smtpd_relay_restrictions =
diff --git a/core/postfix/conf/master.cf b/core/postfix/conf/master.cf
index b43095e..fca83a2 100644
--- a/core/postfix/conf/master.cf
+++ b/core/postfix/conf/master.cf
@@ -3,6 +3,7 @@

 # Exposed SMTP service
 smtp      inet  n       -       n       -       -       smtpd
+  -o smtpd_reject_unlisted_recipient=yes

 # Internal SMTP service
 10025     inet  n       -       n       -       -       smtpd
```

**Comment by bolet** [comment] 2020-07-03 18:07
I haven't tried systematically all possible combinations of the changes but here are my tentative explanations:

- As I understand, the mailu setup, all incoming SMTP connections go through the "front" container (nginx) which is on SUBNET, so accepting SUBNET without authentication is probably the cause of the open relay.
- RELAYNETS is also probably useless in "mynetworks" because of the same reason (all connections come from "front"), so removing it will have no effect.
- I had to add "permit_sasl_authenticated" to compensate the above restriction, or else no email could be sent.
- "reject_unauth_destination" is an additional restriction which didn't harm any subsequent tests.
- "smtpd_reject_unlisted_recipient=yes" solved another issue where mails for non-existing users were not rejected. Though less important than the open relay issue, it's probably a better behaviour to reject those emails than silently discard them.

**Comment by Nebukadneza** [comment] 2020-08-18 18:13
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by liquidat** [comment] 2020-08-25 13:33
@bolet I cannot reproduce this: in a default setup of mailu I was not able to use it as an open relay. The usual available tests online like mtooblox also were not able to use my system as a default relay.

Can you please prove more information on your setup? Is there an additional nginx server or something in front? Do you use IPv6 in your mail setup? And what environment are you running on, kubernetes, compose, etc?

**Comment by Diman0** [comment] 2020-09-25 20:28
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Closed by Diman0** 2020-09-25 20:28 UTC
Labels: status/response_needed

**Comment by bolet** [comment] 2020-10-13 12:17
> @bolet I cannot reproduce this: in a default setup of mailu I was not able to use it as an open relay. The usual available tests online like mtooblox also were not able to use my system as a default relay.
> 
> Can you please prove more information on your setup? Is there an additional nginx server or something in front? Do you use IPv6 in your mail setup? And what environment are you running on, kubernetes, compose, etc?

My setup was indeed special I guess : I deployed the mailu stack inside a libvirt based VM. All incoming connections (from the public interface of the host) were tagged as coming from the host machine (whose IP address was considered local by mailu). Hence the "open relay" issue I had.

As a follow-up, IP routing with libvirt showed to have other reliability issues, so I ended up switching to socat on the host machine to forward connections. socat also masquerades the IP of the original sender. So my patch is still useful there.

I don't know if this kind of setup is common enough to justify a change upstream, but for myself I have to keep working on a branch.

**Comment by mxvin** [comment] 2020-10-16 16:56
Heck! I just got spam too, sending bunch email to @yahoo.co.jp domain, Yahoo MTA seems not happy about it, they said `[TSS04] Messages from <my ip> temporarily deferred due to user complaints - 4.16.55.1; see https://postmaster.verizonmedia.com/error-codes`. But mxtoolbox.com said my mailserver not being an open relay. Is that because behind nginx? then postfix detect legitimate local mail traffic... I just don't understand 😞

**Comment by p4ck3t0** [comment] 2020-12-25 01:52
Mailu per default is indeed a open relay!
The fixes above from @botlet does fix this. I also created an Issue where the open relay is IPv6 related. I've noiced, that the autoresponder didn't work after you remove `{{ SUBNET }} {{ RELAYNETS }}` from mynetworks.

**Comment by bolet** [comment] 2020-12-25 15:57
@p4ck3t0 I admit I didn't do extensive testing after I removed those variables, sorry. The autoresponder mails probably come from another mailu container, so I believe restoring the `{{ SUBNET }}` part would fix your issue, hopefully not reopening the relay.

The best fix would be to set `SUBNET` and `RELAYNETS` to sensible values. A more knowledgeable contributor is welcome here :-)

BTW, my nick is @bolet :-p

**Comment by bolet** [comment] 2020-12-25 16:03
> Is that because behind nginx? then postfix detect that as a legitimate local mail traffic that can be relayed

@mxvin This is exactly my assumption. If it's right I'm afraid we have a real architecture problem here.

**Comment by p4ck3t0** [comment] 2020-12-25 16:10
Ups, my auto correction got me @bolet. XD

You don't have to apologize for your testing.
You're right, we can set `{{ SUBNET }}` to just the IP-Address of the IMAP Container. Then the auto responder is woking as expected.

The main issue here still is that our postfix is reverse proxied, so we should never trust the proxy, because everything from the internet is passed through it. So we trust the whole internet...

From my perspective, the best solution should be to publish the ports directly from postfix, but I think this causes many changes in the mailu environment.

**Comment by bolet** [comment] 2020-12-25 16:27
> the best solution should be to publish the ports directly from postfix

Letting `nginx` reverse-proxy incoming connections makes it the only component having to deal with SSL stuff. Like reloading the config on certificates renewal. To me, this choice is elegant. But it takes some more attention to... well stuff like this bug.

In this architecture we should either trust:
- `SUBNET - nginx`.
- Only those containers who really have to send emails on our behalf, which is at least the one autoresponding (I understand it's `dovecot`).

If `172.24.0.8` is hard coded in the `Dockerfile` then it's probably fine to hard code it also in `mynetworks`.

**Comment by nextgens** [comment] 2024-08-04 08:00
@spoooyders this is a 4 year old issue that should never have been filed.

From your logs you can see that Mailu sees that the 'spammer' is from 192.168.210.1. This most likely means that some form of NAT is masquerading the real ip address *before* it reaches Mailu. Fix that and your problem will be gone.

As for testing your setup with swaks... this will and should always work if you test from localhost.

File a support request under 'discussion' if you need further assistance.
