### ISSUE TITLE
new install master / latest - 404 after adding a user, user is added

### ISSUE THREAD

**Issue by outbackdingo** [Mailu/Mailu#442] opened 2018-04-11 19:21 UTC
So, Ive spun up a new host with docker only and deployed a standard docker-compose   mailu based on master with the latest images, all seems working, however as admin when adding email users after clicking submit i am getting a 404 error, it does however add the user fine.

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by outbackdingo** [comment] 2018-04-12 08:31
148.251.24.4 - - [12/Apr/2018:08:27:27 +0000] "GET /static/bootstrap/jquery.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.0" 200 - "https://mail.optimcloud.nl/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:27 +0000] "GET /static/bootstrap/js/bootstrap.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.0" 200 - "https://mail.optimcloud.nl/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:27 +0000] "GET /ui/static/select2/js/select2.min.js HTTP/1.0" 200 - "https://mail.optimcloud.nl/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:27 +0000] "GET /ui/static/adminlte/js/app.min.js HTTP/1.0" 200 - "https://mail.optimcloud.nl/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:32 +0000] "GET /ui/domain HTTP/1.0" 200 5789 "https://mail.optimcloud.nl/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:35 +0000] "GET /ui/user/list/optimcloud.nl HTTP/1.0" 200 5822 "https://mail.optimcloud.nl/admin/ui/domain" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
148.251.24.4 - - [12/Apr/2018:08:27:37 +0000] "GET /ui/user/create/optimcloud.nl HTTP/1.0" 200 7958 "https://mail.optimcloud.nl/admin/ui/user/list/optimcloud.nl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
[2018-04-12 08:28:21,326] ERROR in app: Exception on /ui/user/create/optimcloud.nl [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 28, in wrapper
    return callback(function, args, kwargs, dargs, dkwargs)
  File "/app/mailu/ui/access.py", line 19, in callback
    return function(*args, **kwargs)
  File "/app/mailu/ui/views/users.py", line 38, in user_create
    user.send_welcome()
  File "/app/mailu/models.py", line 254, in send_welcome
    app.config["WELCOME_BODY"])
  File "/app/mailu/models.py", line 170, in sendmail
    smtp.sendmail(from_address, [self.email], msg.as_string())
  File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'scottk@optimcloud.nl': (553, b'5.7.1 <admin@optimcloud.nl>: Sender address rejected: not logged in')}
148.251.24.4 - - [12/Apr/2018:08:28:21 +0000] "POST /ui/user/create/optimcloud.nl HTTP/1.0" 500 291 "https://mail.optimcloud.nl/admin/ui/user/create/optimcloud.nl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

**Comment by steamedhams1** [comment] 2018-04-12 10:03
I'm having the same issue; currently running version 1.5. I suppose since the user is created despite the error it's more of an irritant than a hindrance, but still. Relevant logs are below. 
`4/12/2018 2:48:57 AM10.42.11.97 - - [12/Apr/2018:09:48:57 +0000] "GET /ui/user/create/theoasis.duckdns.org HTTP/1.0" 200 7949 "http://mailu.theoasis.duckdns.org/admin/ui/user/list/theoasis.duckdns.org" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
4/12/2018 2:49:09 AM[2018-04-12 09:49:09,712] ERROR in app: Exception on /ui/user/create/theoasis.duckdns.org [POST]
4/12/2018 2:49:09 AMTraceback (most recent call last):
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
4/12/2018 2:49:09 AM    response = self.full_dispatch_request()
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
4/12/2018 2:49:09 AM    rv = self.handle_user_exception(e)
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
4/12/2018 2:49:09 AM    reraise(exc_type, exc_value, tb)
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
4/12/2018 2:49:09 AM    raise value
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
4/12/2018 2:49:09 AM    rv = self.dispatch_request()
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
4/12/2018 2:49:09 AM    return self.view_functions[rule.endpoint](**req.view_args)
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
4/12/2018 2:49:09 AM    return func(*args, **kwargs)
4/12/2018 2:49:09 AM  File "/app/mailu/ui/access.py", line 28, in wrapper
4/12/2018 2:49:09 AM    return callback(function, args, kwargs, dargs, dkwargs)
4/12/2018 2:49:09 AM  File "/app/mailu/ui/access.py", line 19, in callback
4/12/2018 2:49:09 AM    return function(*args, **kwargs)
4/12/2018 2:49:09 AM  File "/app/mailu/ui/views/users.py", line 38, in user_create
4/12/2018 2:49:09 AM    user.send_welcome()
4/12/2018 2:49:09 AM  File "/app/mailu/models.py", line 253, in send_welcome
4/12/2018 2:49:09 AM    app.config["WELCOME_BODY"])
4/12/2018 2:49:09 AM  File "/app/mailu/models.py", line 169, in sendmail
4/12/2018 2:49:09 AM    smtp.sendmail(from_address, [self.email], msg.as_string())
4/12/2018 2:49:09 AM  File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
4/12/2018 2:49:09 AM    raise SMTPRecipientsRefused(senderrs)
4/12/2018 2:49:09 AMsmtplib.SMTPRecipientsRefused: {'test@theoasis.duckdns.org': (553, b'5.7.1 <admin@theoasis.duckdns.org>: Sender address rejected: not logged in')}
4/12/2018 2:49:09 AM10.42.11.97 - - [12/Apr/2018:09:49:09 +0000] "POST /ui/user/create/theoasis.duckdns.org HTTP/1.0" 500 291 "http://mailu.theoasis.duckdns.org/admin/ui/user/create/theoasis.duckdns.org" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"`

**Comment by wilibox** [comment] 2018-08-23 12:28
I am having the same problem when trying to add new users with default settings 1.5 version.

root user was created by following this example:
`docker-compose run --rm admin python manage.py admin root example.net password`

contaner log:
```admin_1      | [2018-08-23 12:04:49,091] ERROR in app: Exception on /ui/user/create/wilibox.com [POST]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 28, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/users.py", line 38, in user_create
admin_1      |     user.send_welcome()
admin_1      |   File "/app/mailu/models.py", line 253, in send_welcome
admin_1      |     app.config["WELCOME_BODY"])
admin_1      |   File "/app/mailu/models.py", line 169, in sendmail
admin_1      |     smtp.sendmail(from_address, [self.email], msg.as_string())
admin_1      |   File "/usr/local/lib/python3.7/smtplib.py", line 881, in sendmail
admin_1      |     raise SMTPRecipientsRefused(senderrs)
admin_1      | smtplib.SMTPRecipientsRefused: {'new@wilibox.com': (553, b'5.7.1 <admin@wilibox.com>: Sender address rejected: not logged in')}```

**Comment by kaiyou** [comment] 2018-10-07 10:15
This is a different issue, and duplicate of #517

**Closed by kaiyou** 2018-10-07 10:15 UTC
