### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by mamdoohi** [Mailu/Mailu#371] opened 2018-01-21 13:36 UTC
hi,
i have a question.
how to attach file above 1M in Mailu ? :)
Thanks.

**Comment by kaiyou** [comment] 2018-01-21 13:58
You should actually be able to. Which version and which Webmail are you using?

**Comment by mamdoohi** [comment] 2018-01-22 04:44
Version: 1.10.3.151

**Comment by kaiyou** [comment] 2018-01-27 10:07
Sorry for the delays, but I meant what version of Mailu (1.4, 1.5 ?) and which Webmail (Roundcube, Rainloop) ?

**Comment by mamdoohi** [comment] 2018-01-27 17:50
i use rainloop. but i can't find mailu version. i use from docker since 2017-09-02

**Comment by kaiyou** [comment] 2018-01-28 09:30
Okay, I was able to reproduce the issue, looking at it right now.

**Comment by kaiyou** [comment] 2018-01-28 09:36
Just pushed a fix to ``master``, I will backport it to stable once approved on the test server.

**Comment by mamdoohi** [comment] 2018-01-28 17:36
Thanks a lot man :)

**Comment by kaiyou** [comment] 2018-01-31 07:23
Sorry for the delay, you could simply use ``master`` temporarily for your frontend image, but it looks like you are using Mailu 1.4, aren't you? The version is specified in your ``.env``.

**Comment by kaiyou** [comment] 2018-02-19 13:18
This was cherry-picked in stable.

**Closed by kaiyou** 2018-02-19 13:18 UTC
Labels: bug
