### ISSUE TITLE
forward emails: bad address

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#141] opened 2017-01-02 09:44 UTC
When I enable Auto-forward in admin interface with an email address contains '+' character, the imap failed with error message:
lmtp: Error: sendmail: bad address 'test+abc@gmail.com'

"Send message copy to..." filter in roundcube works fine also with the '+' character...

**Comment by kaiyou** [comment] 2017-01-02 11:46
It sounds like a bug with our sieve script. I will compare with the one generated by roundcube.

**Comment by kaiyou** [comment] 2017-01-15 16:44
I can indeed reproduce on ``latest`` but not ``stable``, this is due to the Sendmail script to support multiple recipients and not to a sieve script. I will investigate further.

**Comment by kaiyou** [comment] 2017-01-15 20:23
The sendmail script is using the Busybox ``sendmail`` command which actually performs an unusual validation on the recipient string, rejecting many valid characters like ``+``.

We should probably report this while switching to something more robust for sending the email, still no idea what.

**Comment by kaiyou** [comment] 2017-02-02 20:39
After the many bugs that we encountered with forwarding, I just switched to handling forwads as aliases with local copy in Postfix directly. The bug should be fixed in ``master`` (18834de56e2bb62e97150ca9ee8b117d24937609)

**Closed** 2017-02-12 15:49 UTC
Labels: bug
