### ISSUE TITLE
rmilter is not started due to missing glibc pthread_setname_np symbol in alpine:edge

### ISSUE THREAD

**Issue by pesimon** [Mailu/Mailu#137] opened 2016-12-27 06:25 UTC
```
# docker run -d mailu/rmilter:stable
186e90e35bc1707a66e2f5b9e86c8e3b2c259375c3e02d790af9f50115189a7d

# docker logs 186e90e35bc1
Error relocating /usr/lib/libglib-2.0.so.0: pthread_setname_np: symbol not found
rsyslogd: [origin software="rsyslogd" swVersion="8.20.0" x-pid="9" x-info="http://www.rsyslog.com"] start
```

No rmilter process running
```
# docker exec  -ti 186e90e35bc1707a66e2f5b9e86c8e3b2c259375c3e02d790af9f50115189a7d ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 {start.sh} /bin/sh /start.sh
    9 root       0:00 rsyslogd -n
   18 root       0:00 ps -ef
```

It seams to be an issue with alpine and can be reproduced like this
```
$ docker run -ti alpine:edge /bin/sh
/ #
/ #
/ # echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
/ # apk add --update rmilter@testing
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/11) Installing libffi (3.2.1-r2)
(2/11) Installing libintl (0.19.8.1-r0)
(3/11) Installing libuuid (2.28.2-r1)
(4/11) Installing libblkid (2.28.2-r1)
(5/11) Installing libmount (2.28.2-r1)
(6/11) Installing pcre (8.39-r0)
(7/11) Installing glib (2.50.2-r0)
(8/11) Installing hiredis (0.13.3-r0)
(9/11) Installing libmilter (1.0.2-r5)
(10/11) Installing opendkim-libs (2.10.3-r4)
(11/11) Installing rmilter@testing (1.10.0-r0)
Executing rmilter-1.10.0-r0.pre-install
Executing busybox-1.25.1-r0.trigger
Executing glib-2.50.2-r0.trigger
Error relocating /usr/lib/libglib-2.0.so.0: pthread_setname_np: symbol not found
ERROR: glib-2.50.2-r0.trigger: script exited with error 127
OK: 9 MiB in 22 packages
/ # exit
```

**Comment by kaiyou** [comment] 2016-12-27 13:23
This seems to be a duplicate of #133, specifically for ``rmilter``. Probably the same patch will do. Could anyone try and check?

**Comment by pesimon** [comment] 2016-12-27 22:19
Thanks for the hint... that fix from #133 works. 

```
diff --git a/rmilter/Dockerfile b/rmilter/Dockerfile
index 4199985..00caf70 100644
--- a/rmilter/Dockerfile
+++ b/rmilter/Dockerfile
@@ -1,6 +1,7 @@
 FROM alpine:edge

 RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
+ && apk add --no-cache --upgrade musl musl-utils \
  && apk add --update \
      rmilter@testing rsyslog \
  && rm -rf /var/cache/apk/*
@@ -10,4 +11,4 @@ COPY rsyslog.conf /etc/rsyslog.conf
```
Will create a PR

**Comment by kaiyou** [comment] 2016-12-27 22:21
I just removed that fix: it seems it was fixed upstream in the meantime. Struggling with the latest builds of the IMAP container, but all should be fixed in a couple minutes now.

**Comment by pesimon** [comment] 2016-12-27 22:41
works with `mailu/rmilter:latest              b957c59c9533` now

**Comment by kaiyou** [comment] 2016-12-27 22:42
Perfect, still waiting for Dovecot build to finish (unrelated failure due to inconsistent ABI builds on Alpine) and I will close this. Stable branch should be fine too.

**Closed** 2016-12-27 23:00 UTC
Labels: bug
