### ISSUE TITLE
Postfix AWS SES, forwarding emails to external domains

### ISSUE THREAD

**Issue by spinanicky** [Mailu/Mailu#2456] opened 2022-09-24 14:05 UTC
### Environment
 - docker-compose V2.6.0

### Versions
Mailu V 1.9

## Description
I would like to forward person1@mydomain.com to person1@gmail.com through Amazon SES. Trying to do so results in "554: Email address not verified" response from AWS. This is because it is trying to preserve the header of the original sender. Eg: me@gmail.com -> person1@mydomain.com -> person1@gmail.com    -   AWS sees this email as coming from me@gmail.com rather than person1@mydomain.com. 

`2022-09-24T07:38:21.105514+00:00 4a7723cf9f4c postfix/smtp[253974]: 8712B260544: to=<person1@gmail.com>, orig_to=<person1@mydomain.org>, relay=email-smtp.eu-central-1.amazonaws.com[52.58.161.38]:25, delay=8.9, delays=4.6/0.14/2.7/1.4, dsn=5.0.0, status=bounced (host email-smtp.eu-central-1.amazonaws.com[52.58.161.38] said: 554 Message rejected: Email address is not verified. The following identities failed the check in region EU-CENTRAL-1: Me <me@gmail.com> (in reply to end of DATA command))`

## Replication Steps
- Setup outgoing emails to relay over AWS SES
- Setup a forwarding rule for one of your email addresses (person1@mydomain.com) to an external domain (yahoo, gmail, outlook)
- Send an email from gmail to person1@mydomain.com
- Above should appear in postfix log

## Expected behaviour
The behaviour is somewhat expected and a solution is provided here:
https://serverfault.com/questions/499955/aws-ses-email-address-is-not-verified-error-with-postfix-relay

in main.cf

```
sender_canonical_maps = regexp:/etc/postfix/sender_canonical
sender_canonical_classes = envelope_sender
smtpd_data_restrictions = check_sender_access pcre:/etc/postfix/sender_access
```

In /etc/postfix/sender_canonical add

`/.*/    mysenderaddress@example.com
`
In /etc/postfix/sender_access add

`/(.*)/  prepend X-Envelope-MailFrom: <$1>
`
##Problem
I believe we can override main.cf however the sender_canonical and sender_access files can not be overriden as far as I am aware. Could we add a flag so that these are auto configured if SES or some other relay is activated?

## Logs

`2022-09-24T07:38:21.105514+00:00 4a7723cf9f4c postfix/smtp[253974]: 8712B260544: to=<person1@gmail.com>, orig_to=<person1@mydomain.org>, relay=email-smtp.eu-central-1.amazonaws.com[52.58.161.38]:25, delay=8.9, delays=4.6/0.14/2.7/1.4, dsn=5.0.0, status=bounced (host email-smtp.eu-central-1.amazonaws.com[52.58.161.38] said: 554 Message rejected: Email address is not verified. The following identities failed the check in region EU-CENTRAL-1: Me <me@gmail.com> (in reply to end of DATA command))`

**Comment by nextgens** [comment] 2022-09-25 12:03
There are other variables at play here. Mailu uses https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme

The easy solution is to not use SES for emails to person1@gmail.com... you can override specific destinations in mailu by domain using a "more specific relay" or by destination using a postfix override

**Comment by spinanicky** [comment] 2022-09-25 12:21
> The easy solution is to not use SES for emails to [person1@gmail.com](mailto:person1@gmail.com)... you can override specific destinations in mailu by domain using a "more specific relay" or by destination using a postfix override

I appreciate the response @nextgens - I believe we should consider people are using SES for a reason though. Simply turning it off for a specific route may not be possible.

**Comment by nextgens** [comment] 2022-09-25 12:49
I am sorry but I don't know what to make of your report. The first line of the section "expected behaviour" reads "the behaviour is somewhat expected".

What are you expecting here? Should something change? What would be the reason for the change? Most people are happy with a sane email system and do not expect it to arbitrarily rewrite headers just to bypass some restriction put in place by a 3rd party service.

**Comment by nextgens** [comment] 2022-09-25 12:55
I have ended googleing it up for you: others seem to have the same predicament and their solution has been to reply on a sieve script.

The said script and instructions can be found at https://github.com/mailcow/mailcow-dockerized/issues/2944

I'll close this ticket now and if you do think that something in Mailu should change, please open another one explaining clearly what is expected. "3rd party service not happy" type of queries are likely to lead to "don't use 3rd party" responses.

**Closed by nextgens** 2022-09-25 12:55 UTC
