### ISSUE TITLE
Roundcube settings override not working

### ISSUE THREAD

**Issue by SoupDMC** [Mailu/Mailu#2388] opened 2022-07-10 23:05 UTC
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
*.inc files in overrides/roundcube/ dont seem to override any settings in the mailu_webmail_1 containers config.inc.php

## Replication Steps
install mailu, place *.inc file in overrides/roundcube

## Expected behaviour
settings are overriden

**Comment by Diman0** [comment] 2022-07-14 08:15
This information is not sufficient for reproducing the described issue. Required as well are the 
- docker-compose.yml file
- mailu.env file (make sure to remove the SECRET_KEY value, any domains can be removed as well)
- *.inc file that appears not to be used.

**Comment by DannyDaemonic** [comment] 2022-08-16 09:55
I just ran across this myself. The issue here is that you have to start your override files with: `<?php`

This is confusing because you are asking the user for `.inc` files instead of `.inc.php` files. As such, it's not immediately obvious the files require a php "header." One might assume as I had, that they are being `cat`'ed onto the end of a config file. I assume this is also what happened to @SoupDMC.

I don't know how common of a mistake this is but I certainly wouldn't recommend not escaping override `.inc` files. I think the correct thing to do for backwards compatibility would be to _also_ include all `.inc.php` files and update the docs from:
`Roundcube - All *.inc files in the roundcube sub directory.`
to:
`Roundcube - All *.inc.php files in the roundcube sub-directory.`

While we're fixing the docs, the other projects listed in the override section have links to their configuration documentation, but there's none for roundcube.

The official documentation is here:
https://github.com/roundcube/roundcubemail/wiki/Configuration

But it feels mostly incomplete and mostly focuses on things mailu configures for users.  Perhaps it should instead link to the official `defaults.inc.php` file, as the file is fairly well documented and rarely changes:
https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php

**Comment by Diman0** [comment] 2022-08-19 18:31
We will gladly accept a PR that clarifies the above in the documentation.

**Comment by DannyDaemonic** [comment] 2022-08-19 19:55
My suggestions include changing the include file names to their proper extension. I'm open to making a pull request that encompases my entire suggestion.

**Comment by Diman0** [comment] 2022-08-19 20:29
That is fine with me. When creating the [changelog](https://mailu.io/1.9/contributors/workflow.html#changelog), do mention in it that .inc.php should be used from now on. That way we don't forget to mention this in the release notes once the next version if released. From all the newsfragments we derive what should be mentioned in the release notes or not.

**Comment by Diman0** [comment] 2022-08-24 07:05
Closing this issue. Documentation has been updated.

**Closed by Diman0** 2022-08-24 07:05 UTC
Labels: type/enhancement, type/documentation
