### ISSUE TITLE
Generate keys 500 error

### ISSUE THREAD

**Issue by farwydi** [Mailu/Mailu#1020] opened 2019-05-15 12:49 UTC
Hello

Used Mailu 1.6 in docker after first start, i have error 500 on click "Generate keys".

![image](https://user-images.githubusercontent.com/5041061/57776475-3b5f2880-7728-11e9-98ea-acf1755a0853.png)

```
[2019-05-15 12:43:13,554] ERROR in app: Exception on /ui/domain/genkeys/farwydi.ru [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 28, in wrapper
    return callback(function, args, kwargs, dargs, dkwargs)
  File "/app/mailu/ui/access.py", line 19, in callback
    return function(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 108, in wrapper
    form=form
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/mailu/ui/templates/confirm.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/app/mailu/ui/templates/base.html", line 3, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/app/mailu/ui/templates/base.html", line 63, in block "body"
    {% block content %}{% endblock %}
  File "/app/mailu/ui/templates/confirm.html", line 12, in block "content"
    {% call macros.box(theme="warning") %}
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/app/mailu/ui/templates/macros.html", line 79, in template
    {{ caller() }}
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/app/mailu/ui/templates/confirm.html", line 13, in template
    <p>{% trans action %}You are about to {{ action }}. Please confirm your action.{% endtrans %}</p>
  File "/usr/lib/python3.6/site-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
  File "/usr/lib/python3.6/site-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character ' ' (0x20) at index 35
172.18.0.3 - - [15/May/2019:12:43:13 +0000] "GET /ui/domain/genkeys/farwydi.ru HTTP/1.0" 500 291 "https://mail.farwydi.ru/madmin/ui/domain/details/farwydi.ru" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
```

**Comment by kaiyou** [comment] 2019-06-28 13:58
This seems to be a duplicate of #943, I am closing this one.

**Closed by kaiyou** 2019-06-28 13:58 UTC
