### ISSUE TITLE
Strange problem with GMX Mails -- Can not receive any mails from gmx

### ISSUE THREAD

**Issue by NikyMandl** [Mailu/Mailu#3125] opened 2024-01-09 07:50 UTC
hello.

i am having 2 mailu instances.
one older 1.9 und one newer 2.0
on both mailu all is working fine with all mails, but mails from gmx are not working any more.
made no updates on instance with 1.9, and it worked a few weeks ago with gmx mails.

made update of the second instance from 1.9 to 2.0 today, but same problem, also with the new major relase.
Also all is working fine with all mails, only gmx is not working.

i made my tests with an gmx account with domain gmx.at

i added the gmx.at domain in
mailu web interface -> antispam -> configuration -> /etc/rspamd/local.d/maps.d/greylist-whitelist-domains.inc

now i can see the mails in
mailu web interface -> antispam -> history
but it is looking crazy for me.
Seams that header infos are lost when receiving this mail in mailu.
receiving same gmx mails in gmail, echange, yahoo is possible and will be shown correct.

see attached jpg

![crazy_gmx](https://github.com/Mailu/Mailu/assets/94847900/e4c5fceb-7669-4c0e-90df-9c26f334d46c)

All is looking fine in Docker on Mailu version 2.0

99dd209207fc ghcr.io/mailu/fetchmail:2.0 "/fetchmail.py" 2 hours ago Up About an hour (healthy) mailu-fetchmail-1
74dcb4a9d642 ghcr.io/mailu/webmail:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-webmail-1
6bcadae76b6e ghcr.io/mailu/postfix:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-smtp-1
0c7a12ca8e64 ghcr.io/mailu/dovecot:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) 110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp mailu-imap-1
1c41c07bc51c ghcr.io/mailu/rspamd:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-antispam-1
04ce86e57ff3 ghcr.io/mailu/admin:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-admin-1
e982f2d147e7 ghcr.io/mailu/clamav:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-antivirus-1
7b8c5b41764d redis:alpine "docker-entrypoint.s…" 2 hours ago Up About an hour 6379/tcp mailu-redis-1
ef115bd974e8 ghcr.io/mailu/oletools:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-oletools-1
769d0ed92bd7 ghcr.io/mailu/nginx:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) 192.168.1.5:25->25/tcp, 192.168.1.5:80->80/tcp, 192.168.1.5:110->110/tcp, 192.168.1.5:143->143/tcp, 192.168.1.5:443->443/tcp, 192.168.1.5:465->465/tcp, 192.168.1.5:587->587/tcp, 192.168.1.5:993->993/tcp, 192.168.1.5:995->995/tcp mailu-front-1
4bbe8da4b6bf ghcr.io/mailu/unbound:2.0 "/bin/sh -c /start.py" 2 hours ago Up About an hour (healthy) mailu-resolver-1
66e2e15f30d6 ghcr.io/mailu/radicale:2.0 "/bin/sh -c 'radical…" 2 hours ago Up About an hour (healthy) mailu-webdav-1
9d0bb5168b00 nginx:latest "/docker-entrypoint.…" 11 months ago Exited (0) 11 months ago mailu-web-1
2aff25bffbc3 php:7-fpm "docker-php-entrypoi…" 11 months ago Exited (0) 11 months ago mailu-php-1

Please guide and help me,
i dont now what is happening here.

i think gmx changed something but i am not sure...

is there anything i can do ???

best regards, Niky

**Comment by nextgens** [comment] 2024-01-09 08:36
duplicate of #3122

**Closed by nextgens** 2024-01-09 08:36 UTC
