### ISSUE TITLE
"Request failed" in Snappymail when displaying one specific INBOX folder

### ISSUE THREAD

**Issue by Ezwen** [Mailu/Mailu#3401] opened 2024-09-04 06:54 UTC
## Environment & Version

- `docker compose version` : `v2.29.1`
- Version: `2024.06.12`

## Description

For one specific INBOX folder or one specific email account, Snappymail fails to displays the INBOX folder contents, and displays "_Request failed_" instead.

Displaying content of other folders of the same account work, and other accounts I tested have no such problem either.

Using an external IMAP client to browse this INBOX folder also works perfectly fine.

## Replication Steps

This started happening for no clear reason − although I did have no space remaining on disk shortly before this problem happened (and since then I fixed the space issue).

## Observed behaviour

When I open the webmail with the faulty account, I get this:

![image](https://github.com/user-attachments/assets/f3f0bcf6-76cc-4973-881b-dda0b8a0e269)

In Firefox console logs, I see there is a `500` error, although there is a response which, if I expand it, does contain the list of emails that the UI should display:

![image](https://github.com/user-attachments/assets/16c79615-d937-46c4-af27-8ccc2b590ea9)

## Expected behaviour

I expect the INBOX folder to be displayed as before.

## Logs

In the webmail logs I see this message each time I try to refresh the webmail in the faulty INBOX:

```
2024/09/04 08:43:27 [error] 17#17: *366 FastCGI sent in stderr: "PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_set', because its argument '$option' content (display_errors) matched a rule in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/shutdown.php on line 15" while reading response header from upstream, client: 37.65.66.89, server: , request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mail.enevned.fr"
```

**Comment by nextgens** [comment] 2024-09-04 07:00
If this is happening only for a specific folder of a specific mailbox odds are the indexes are corrupted.

What do the logs of the ``imap`` container tell you when you attempt to access it?

**Comment by Ezwen** [comment] 2024-09-04 07:58
> If this is happening only for a specific folder of a specific mailbox odds are the indexes are corrupted.

I see 😵

> What do the logs of the `imap` container tell you when you attempt to access it?

Just tried and checked, and no error/warning to be found:

```
INFO:root:Connect 
INFO:root:Connect 
Sep 04 09:57:32 imap-login: Info: Login: user=<REDACTED>, method=PLAIN, rip=REDACTED, lip=REDACTED, mpid=1622, secured, session=<av68hkYhOKZPX1Yw>
INFO:root:Connect 
INFO:root:Connect 
Sep 04 09:57:34 imap-login: Info: Login: user=<REDACTED>, method=PLAIN, rip=REDACTED, lip=REDACTED, mpid=1624, secured, session=<F8TghkYhPKZPX1Yw>
Sep 04 09:57:34 imap(REDACTED)<1622><av68hkYhOKZPX1Yw>: Info: Disconnected: Logged out in=2047 out=42583 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Sep 04 09:57:34 imap(REDACTED)<1624><F8TghkYhPKZPX1Yw>: Info: Disconnected: Logged out in=20 out=533 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

**Comment by thijsniehof** [comment] 2024-09-05 06:56
I have the very same issue.. along with some other issues, which led me to testing the different versions.
The issue is on all 4 domains, with all mailbox-users on those domains, except for the mailserver admin user (admin@mailserver.mydomain.com)
I started with version 2004.6.6, then reconfigured my docker compose file for the use of Traefik. When this worked, I started upgrading to 2004.6.7, .8, .9 and so on. I believe it was as of version 2004.6.10 this issue first surfaced.
I don't think it's because of corrupted indexes, because when I downgrade to 2004.6.8 for example, the Inbox does show correctly.
Furthermore: the contents of the Inbox folder is perfectly readable in an IMAP client, it's just the webmail, and only the INBOX folder. Other folders work perfectly in the webmail. And as said, the inbox for the mail admin user doesn't have this issue.
My imap container does not give errors, but my webmail container does:
`[error] 19#19: *352 FastCGI sent in stderr: "PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_set', because its argument '$option' content (display_errors) matched a rule in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/shutdown.php on line 15" while reading response header from upstream, client: 234.123.234.123, server: , request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mailserver.MYDOMAIN"`

**Comment by thijsniehof** [comment] 2024-09-05 14:23
Some more warning/error lines:
```
FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/gpg/pgp.php on line 873; PHP message: PHP Warning:  Array to string conversion in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/gpg/pgp.php on line 873" while reading response header from upstream, client: x.x.x.x, server: , request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mailserver.mydomain"
FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/gpg/pgp.php on line 873; PHP message: PHP Warning:  Array to string conversion in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/gpg/pgp.php on line 873" while reading response header from upstream, client: x.x.x.x, server: , request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mailserver.mydomain"
FastCGI sent in stderr: "PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_set', because its argument '$option' content (display_errors) matched a rule in /var/www/snappymail/snappymail/v/2.36.4/app/libraries/snappymail/shutdown.php on line 15" while reading response header from upstream, client: x.x.x.x, server: , request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mailserver.mydomain"
```

**Comment by nextgens** [comment] 2024-09-05 20:22
Well I've tried reproducing this unsuccessfully. Encrypting/decrypting GPG messages works for me.
![image](https://github.com/user-attachments/assets/67fa18cd-b90b-45e3-8c7b-71fec5272866)


The fatal error you see should not make a difference... but it's fixed on pr-3407.

Once the images are built, please try reproducing it with:
```
export MAILU_VERSION=pr-3407
docker compose pull
docker compose up -d
```

**Comment by thijsniehof** [comment] 2024-09-05 20:25
I never received any GPG messages, therefore the warnings confused me a bit.
I'll test it asap

**Comment by thijsniehof** [comment] 2024-09-05 20:47
This seems to be working! The error went away on all the affected INBOX folders.
Thanks!

**Comment by Ezwen** [comment] 2024-09-05 20:54
I just tried `pr-3407` as well, and indeed the problem from my original post is fixed. Thank you!

**Comment by nextgens** [comment] 2024-09-05 21:02
Great, thank you for confirming

**Closed** 2024-09-07 18:44 UTC
Labels: type/bug
