### ISSUE TITLE
ValueError on domain key generation

### ISSUE THREAD

**Issue by belegnar** [Mailu/Mailu#1043] opened 2019-06-10 12:54 UTC
Locale: ru (how to change to 'en'?)
From admin logs:
```admin_1      | [2019-06-10 12:13:33,735] ERROR in app: Exception on /ui/domain/genkeys/vgent.ru [GET]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 28, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 108, in wrapper
admin_1      |     form=form
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
admin_1      |     context, ctx.app)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
admin_1      |     rv = template.render(context)
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
admin_1      |     return original_render(self, *args, **kwargs)
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
admin_1      |     return self.environment.handle_exception(exc_info, True)
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
admin_1      |     raise value.with_traceback(tb)
admin_1      |   File "/app/mailu/ui/templates/confirm.html", line 1, in top-level template code
admin_1      |     {% extends "base.html" %}
admin_1      |   File "/app/mailu/ui/templates/base.html", line 3, in top-level template code
admin_1      |     {% extends "bootstrap/base.html" %}
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
admin_1      |     {% block doc -%}
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
admin_1      |     {%- block html %}
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
admin_1      |     {% block body -%}
admin_1      |   File "/app/mailu/ui/templates/base.html", line 63, in block "body"
admin_1      |     {% block content %}{% endblock %}
admin_1      |   File "/app/mailu/ui/templates/confirm.html", line 12, in block "content"
admin_1      |     {% call macros.box(theme="warning") %}
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
admin_1      |     rv = self._func(*arguments)
admin_1      |   File "/app/mailu/ui/templates/macros.html", line 79, in template
admin_1      |     {{ caller() }}
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
admin_1      |     rv = self._func(*arguments)
admin_1      |   File "/app/mailu/ui/templates/confirm.html", line 13, in template
admin_1      |     <p>{% trans action %}You are about to {{ action }}. Please confirm your action.{% endtrans %}</p>
admin_1      |   File "/usr/lib/python3.6/site-packages/jinja2/ext.py", line 143, in gettext
admin_1      |     return rv % variables
admin_1      |   File "/usr/lib/python3.6/site-packages/markupsafe/__init__.py", line 102, in __mod__
admin_1      |     return self.__class__(text_type.__mod__(self, arg))
admin_1      | ValueError: unsupported format character ' ' (0x20) at index 35
```

**Comment by kaiyou** [comment] 2019-06-28 14:01
This is a duplicate of #943 which we will prioritize. Thanks for the stack trace, which helps :)

**Closed** 2019-06-28 14:01 UTC
