### ISSUE TITLE
Mailu Antivirus Clam does Nothing

### ISSUE THREAD

**Issue by yatadev** [Mailu/Mailu#1728] opened 2021-01-14 08:51 UTC
### Environment
 - [x ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
Mailu 1.7

## Description
The Clam container finds the Virus 3 Times (because i mailed it to myself)

ANTIVIRUS_ACTION=reject and the default one, both do nothing after finding the Virus.

## Replication Steps
- Install mailu 1.7 per docker-compose
- activate clamav as antivirus
- send some virus file to yourself (use a virus clam knows...) 
- you will recieve the file

## Expected behaviour
default options:
  virus should get silently deleted

ANTIVIRUS_ACTION=reject:
  email should not be sent at all

## Logs

````markdown
```
Thu Jan 14 08:47:06 2021 -> instream(172.18.1.10@48020): Win.Trojan.Mimikatz-6466236-0 FOUND
Thu Jan 14 08:47:11 2021 -> instream(172.18.1.10@48028): Win.Trojan.Mimikatz-6466236-0 FOUND
Thu Jan 14 08:47:14 2021 -> instream(172.18.1.10@48042): Win.Trojan.Mimikatz-6466236-0 FOUND

```
````

**Comment by Diman0** [comment] 2021-02-02 12:46
ANTIVIRUS_ACTION=reject is introduced in Mailu 1.8. The option does not exist in Mailu 1.7.

Can you check if your mailu.env file contains the line
```
ANTIVIRUS=clamav
```
In an older version of the setup website there was a bug. It would creating this line in comment in your generated mailu.env file
```
#ANTIVIRUS=clamav
```

I cannot replicate this. I can see nicely in the antispam (rspamd) web gui that the virus is recognized and the email is subsequently not delivered. 

Can you see in the rspamd gui that clamav is used? In the history tab it should be shown as one of the symbols.
Or you could check the logs of the antispam container. The is how it is logged:
```
0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; milter; rspamd_milter_process_command: got connection from 172.19.0.9:34698
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; rspamd_message_parse: loaded message; id: <139c9b0edbf604b9ef8cc19409e34db2@doe.com>; queue-id: <3FE6D760BAC>; size: 1759; checksum: <b761d81ecd14820fa5d787fa0dc1f429>
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; greylist.lua:183: skip greylisting for local networks and/or authorized users
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; rspamd_mime_part_detect_language: detected part language: nl
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; spf_symbol_callback: skip SPF checks for local networks and authorized users
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; once_received.lua:95: Skipping once_received for authenticated user or local network
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; dmarc.lua:573: skip DMARC checks for local networks and authorized users
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; ip_score.lua:326: skip IP Score for authorized users

**ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; common.lua:102: clamav: result - virusfound: "Win.Test.EICAR_HDB-1 - score: 1"**

ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; bayes_classify: skip classification as ham class has not enough learns: 0, 200 required
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; lua; greylist.lua:297: Score too low - skip greylisting
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; rspamd_task_write_log: id: <139c9b0edbf604b9ef8cc19409e34db2@doe.com>, qid: <3FE6D760BAC>, ip: 172.19.0.9, user: john@doe.com, from: <john@doe.com>, (default: F (no action): [-0.09/15.00] [MIME_BAD_EXTENSION(4.00){com;},REPLY(-4.00){},MIME_GOOD(-0.10){multipart/mixed;text/plain;},ARC_NA(0.00){},ARC_SIGNED(0.00){i=1;},CLAM_VIRUS(0.00){Win.Test.EICAR_HDB-1;},DKIM_SIGNED(0.00){},FROM_EQ_ENVFROM(0.00){},FROM_NO_DN(0.00){},HAS_ATTACHMENT(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;1:+;2:-;2:~;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},TO_DN_NONE(0.00){},TO_EQ_FROM(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 1759, time: 151.998ms real, 15.488ms virtual, dns req: 6, digest: <b761d81ecd14820fa5d787fa0dc1f429>, rcpts: <john@doe.com>, mime_rcpts: <john@doe.com>
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <b84395>; proxy; rspamd_protocol_http_reply: regexp statistics: 146 pcre regexps scanned, 1 regexps matched, 185 regexps total, 12 regexps cached, 6.12KiB scanned using pcre, 6.12KiB scanned total
ESC[36mantispam_1   |ESC[0m 2021-02-02 12:40:59 #6(rspamd_proxy) <df634d>; proxy; proxy_milter_finish_handler: finished milter connection
```

**Comment by yatadev** [comment] 2021-02-03 09:39
Ok the reject option does not exist in 1.7. 
But the problem was without reject the same...
It is working now, but i havent changed something, super confused atm....

**Comment by Diman0** [comment] 2021-03-09 09:29
Ok. I'm closing this since we have no reproducible scenario. If the issue comes back in the future and you have a reproducible scenario then you can create a new issue.

**Closed by Diman0** 2021-03-09 09:29 UTC
Labels: status/response_needed
