### ISSUE TITLE
swarm mode (stack deploy) & authentification ?

### ISSUE THREAD

**Issue by ofthesun9** [Mailu/Mailu#530] opened 2018-07-17 09:04 UTC
I am trying to deploy mailu (1.5) under swarm mode (docker stack deploy -c ....)
I modified a little bit the .yml file (I am using nfs volume(s)): 
[docker-compose-stack-simple.txt](https://github.com/Mailu/Mailu/files/2200943/docker-compose-stack-simple.txt)
and if I run the docker-compose with this file, everything is ok, but If I run the file with docker stack deploy, I am unable to login (imap, webmail etc)
I get this in the logs:
mailu-swarm_front.1.weuol4erohw8@coreos-01    | 2018/07/17 08:55:55 [info] 8#8: *31 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: 10.255.0.2 using starttls, server: 0.0.0.0:143, login: "xxxxx@vmaltair.ddns.net", upstream: 10.0.1.14:143

That would be really cool to get swarm mode working (I intend to use some raspberry as workers :-))

**Comment by ofthesun9** [comment] 2018-07-18 12:44
@Wolfboy573 ,  yes the .env file is not supported for substitution *in* the docker-compose.yml itself. That is why I removed the $VERSION and so on in the .yml
But the .env file can be used to pass parameter within the service. I checked with the portainer how my services are deployed and all the environnment file in the .env file are populated.
Basically every services seems to be working (checking the log, they are all running) except the admin or authentification part...
Thanks for pointing #375 ! I will have a look :-)

**Comment by Wolfboy573** [comment] 2018-07-18 12:49
@ofthesun9  Nice, I wasnt that far yet with the params in service. Just started with docker swarm. Im also trying to get mailu on docker swarm. 
This morning I found that request. 
Ill look a bit deeper in your solution.

**Comment by ofthesun9** [comment] 2018-07-18 14:09
@Wolfboy573 , thanks to the description in #375, I got it working ! I had to add "endpoint_mode: dnsrr" in each deploy section:
[docker-compose-stack-simple.txt](https://github.com/Mailu/Mailu/files/2206078/docker-compose-stack-simple.txt)
I guess that it has to do with the Virtual IP mechanism (which is by-passed with the "endpoint_mode: dnsrr")
I will check whether all the services need the statement "endpoint_mode: dnsrr" or only some of them.

Next step : try to deploy some service(s) on another node and check if this working well :-)

**Comment by ofthesun9** [comment] 2018-07-20 17:08
I confirm this is working well. I have deployed 2 smtp, 2 imap, 1 roundcube, 1 antispam on the workers, while the other services are on the manager (I have 1 manager and 2 workers) and this is working great.

**Comment by kaiyou** [comment] 2018-08-01 19:30
Yep, the main issue is with Mailu relying on being able to resolve containers by name. It would be really amazing if you could contribute some documentation lines about using stack with Mailu :)

**Comment by muhlemmer** [comment] 2018-08-07 12:37
@ofthesun9;

As you noted in the PR #551, `dnsrr` prevents the network from being able in `overlay` mode:

> On a swarm, the services are available (default mode) through a routing mesh managed by docker itself. With this mode, each service is given a virtual IP adress and docker manages the routing between this virtual IP and the container(s) provinding this service. With this default networking mode, I cannot get login working properly... As found in https://github.com/Mailu/Mailu/issues/375 , a workaround is to use the dnsrr networking mode at least for the front services.
> 
> The main consequence/limitation will be that the front services will not be available on every node, but only on the node where it will be deployed. In my case, I have only one manager and I choose to deploy the front service to the manager node, so I know on which IP the front service will be available (aka the IP address of my manager node).

However, processes _should_ be perfectly able to resolve hostnames in the docker swarm without `dnsrr`. This problem seems to be more with how php tries to resolve the hostnames `front` and `imap`. For instance in `roundcube`'s `conf.inc.php`:

```
$config['default_host'] = 'front';
...
$config['managesieve_host'] = 'imap';
```
I've modified your `docker-compose.yml` file to use `mode: overlay` for all port mappings (this is the default). Also I removed all `endpoint_mode: dnsrr` .

``` 
 ports:
      - target: 80
        published: 80
        mode: overlay
        ...
````
`docker deploy` still works fine, taking issue #555 into account.

To verify that the hostnames can resolve correctly in this mode:

```
[root@sun mailu]# docker container ls
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
...
ba8822bcef66        mailu/roundcube:1.5     "docker-php-entrypoi…"   12 minutes ago      Up 12 minutes       80/tcp              mailu_webmail.1.85zem7nxh44f0t7pwqkg0fp6x
...
[root@sun mailu]# docker exec ba8822bcef66 getent hosts front
10.0.7.25       front
[root@sun mailu]# docker exec ba8822bcef66 getent hosts imap
10.0.7.19       imap
[root@sun mailu]# docker service inspect --format '{{json .Endpoint.VirtualIPs}}' mailu_front  | jq .
[
  {
    "NetworkID": "l9bdrg3jaze9zq6o62wr2rysd",
    "Addr": "10.255.0.16/16"
  },
  {
    "NetworkID": "4q8rtxewptfqs9fxwwishlhtw",
    "Addr": "10.0.7.25/24"
  }
]
[root@sun mailu]# docker service inspect --format '{{json .Endpoint.VirtualIPs}}' mailu_imap  | jq .
[
  {
    "NetworkID": "4q8rtxewptfqs9fxwwishlhtw",
    "Addr": "10.0.7.19/24"
  }
]
```
So the addresses are resolved to the correct Virtual IP from inside the roundcube container. Also:

1. `front` is perfectly capable of resolving `webmail`, the login page shows up correctly.
2. `admin` page login works as usual. (page display and login)

So it seems an isolated issue of the `webmail` service. My suggestion is to find and fix the real issue, instead of committing these instructions with workarounds.

Related to this is the general issue of incorrect resolving of docker, #555

**Comment by muhlemmer** [comment] 2018-08-07 12:52
@kaiyou;

> Yep, the main issue is with Mailu relying on being able to resolve containers by name. It would be really amazing if you could contribute some documentation lines about using stack with Mailu :)

The main differences:

`docker-compose` tool initiates a container for each `service` entry. Each container receives a bridge network interface, with a IP address. When resolving by name (eg: `front`), it is resolved to the IP of the container.

`docker stack deploy` tool initiates services. Each service is meant to contain multiple container instances from the same image. (Replication). An overlay network is created by default. Now, if you resolve `front` it resolved to a virtual IP, which load balances requests over all container instances from the service.

So, from docker-compose.yml and host name usage, nothing really changes. It is important to know that each TCP session can end up on a different instance of the resolved service.

Any outside client request to `front` can end up at any instance inside the `front` service. Any request from the `front` service can end up at any instance from the smtp/imap/webmail etc. service.

**Comment by muhlemmer** [comment] 2018-08-07 12:58
[This](https://secure.php.net/manual/en/function.gethostbyname.php#111684) might be related:

> If you do a gethostbyname() and there is no trailing dot after a domainname that does not resolve, this domainname will ultimately be appended to the server-FQDN by nslookup.
> 
> So if you do a lookup for nonexistentdomainname.be your server may return the ip for nonexistentdomainname.be.yourhostname.com, which is the server-ip.
> 
> To avoid this behaviour, just add a trailing dot to the domainname; i.e. gethostbyname('nonexistentdomainname.be.')

**Comment by ofthesun9** [comment] 2018-08-07 20:05
@muhlemmer , Hello, could you please indicate where I can find the definition for mode :overlay as indicated:
```
 ports:
      - target: 80
        published: 80
        mode: overlay
        ...
```
in https://docs.docker.com/compose/compose-file/#long-syntax-1 , I only find host or ingress as possible value...
If I remember well, using "host" requires "endpoint_mode: dnsrr" and using ingress (default) requires  
endpoint_mode: vip (default)

Anyway I agree that finding the root cause would be better than defining workarounds, but I am a little bit puzzled because I tried many times the default mode (vip & ingress) and I never could get authentifcation working (imap, smtp, or admin interface)... As soon as I was using host & dnsrr, it was much better (I was hit by #555 as well) and authentification is working....

**Comment by muhlemmer** [comment] 2018-08-07 20:44
https://docs.docker.com/v17.09/engine/userguide/networking/#overlay-networks-in-swarm-mode
https://docs.docker.com/compose/compose-file/#endpoint_mode

Ingress is the default overlay network that covers all services that need an outside link. Next to that a network will be created (something like mailu_default) for communications between containers over all the nodes. See this image:

![Swarm network view](https://neuvector.com/wp-content/uploads/2017/01/swarm_network_view.png)

**Comment by muhlemmer** [comment] 2018-08-08 17:52
The real problem lies at Dovecot user  query. With debuggin enabled:

```
Aug 08 17:22:34 auth-worker(20): Debug: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): query: SELECT NULL as password, 'Y' as nopassword, '10.0.5.11,10.0.5.7' as allow_nets FROM user WHERE user.email = 'user@example.com'
Aug 08 17:22:34 auth-worker(20): Debug: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets: Matching for network 10.0.5.11
Aug 08 17:22:34 auth-worker(20): Debug: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets: Matching for network 10.0.5.7
Aug 08 17:22:34 auth-worker(20): Info: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets check failed: IP 10.0.5.3 not in allowed networks
Aug 08 17:22:34 auth: Debug: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets: Matching for network 10.0.5.11
Aug 08 17:22:34 auth: Debug: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets: Matching for network 10.0.5.7
Aug 08 17:22:34 auth: Info: sql(user@example.com,10.0.5.3,<Jvuhwe9ypKoKAAUD>): allow_nets check failed: IP 10.0.5.3 not in allowed networks
Aug 08 17:22:36 auth: Debug: client passdb out: FAIL    1       user=user@example.com
Aug 08 17:22:36 imap-login: Info: Disconnected (auth failed, 1 attempts in 2 secs): user=<user@example.com>, method=PLAIN, rip=10.0.5.3, lip=10.0.5.16, session=<Jvuhwe9ypKoKAAUD>
```
The Dovecot [query](https://github.com/Mailu/Mailu/blob/f506966abc5ec5452f7db599a11e16d7cc497e80/core/dovecot/conf/dovecot-sql.conf.ext#L6) checks against the IP's of `front` or `webmail`. However, in `start.py` the hostname gets resolved to the Virtual IP. But the dovecot host sees traffic origin from the individual instances (different IP) and denies the auth request.

This has been solved for Kubernetes in commit https://github.com/Mailu/Mailu/commit/6018995534117dee01acb87525c8371c49825d07. I will look how we can sent the Docker swarm subnet address to `POD_ADDRESS_RANGE` variable.

**Comment by muhlemmer** [comment] 2018-08-09 06:53
I git this far: postfix sends `client` to `front` and gets relayed to `admin` service. Over there the authentication request is handed by some python scripts.
[
Here](https://github.com/Mailu/Mailu/blob/f506966abc5ec5452f7db599a11e16d7cc497e80/core/admin/mailu/internal/nginx.py#L45) there is some IP-based checking which _might_ be the issue. But I don't have enough python experience nor mailu knowledge to understand what is exactly happening. Maybe @kaiyou can step in to give some suggestions.

To summarize:

- Docker swarm resolves hosts to a VIP
- The VIP is used for layer 3/4 load balancing
- However, origin information is always an instance IP != VIP.
- Any IP based checking will therefore not work in Swarm mode.
- Subnet checking should be used instead. (host from local network == okay)

`dnsrr` might give the sensation it work, but be warned when replicating. Every lookup to a host gives a different IP. So imagine:
- `webmail_1` tries to resolve `imap` service.
- `dnsrr` resolves to `imap_1` (or 1, 2, n)
- `webmail_1` sends the request to `imap_1`
- `imap_1` tries to resolve `webmail` service
- `dnsrr` can resolve to `imap_2` (or 1, 3, n)
- now the request IP != authorized IP.
This can lead to unstable behavior. Sometimes the hosts are resolved properly towards each other. And sometimes not. Then, some services do their resolving once, during startup and will behave different altogether.

**Comment by muhlemmer** [comment] 2018-08-09 11:08
@ofthesun9; Attached [docker-compose.yml.txt](https://github.com/Mailu/Mailu/files/2273896/docker-compose.yml.txt) with the correct setting to make the IMAP auth work. Note that the  images are pulled from my own Docker hub repository, which are build from my own `testing` branch including commits from PR #560 and #563.

If those PR's are accepted & merged, this issue can be closed and documentation can be updated accordingly. For now you might want to close PR #551, as that information in no longer relevant.

**Comment by fatalsaint** [comment] 2018-08-14 15:51
I can confirm that with a stackfile that uses the master tag of all official mailu upstream containers, except SMTP, and the POD_ADDRESS_RANGE option in the imap container, that email is working properly in swarm with a "mode: global" front (6 nodes).

For SMTP, I had to use muhlemmer's postfix container because of the XCLIENT problem #563.  I have traefik in front of the web portions (webmail, admin) and host port mappings for the 'front' nginx container mail ports.

The nice thing about Mailu is that front-end nginx reverse proxy that preserves real client ip to the mail backend.  In Swarm, the hardest part, is getting real client IP because the standard ingress port mappings don't pass it, so features like SPF do not work, you have to do host port mappings which is less scaleable.

It'll be awesome to see this fixed in a proper release so can use all official upstream images.

**Comment by muhlemmer** [comment] 2018-08-14 17:04
@fatalsaint; I don't recommend pulling my `:testing` images. I'm building those as a playground. I'm using the testing branch on my GitHub form to combine not-yet merged PRs. However, the images do NOT always reflect what's on GitHub. I'm trying different things local, if it works I create a commit, subsequent PR and inclusion in testing.

I have no idea what kind of funny business you pulled in just now. ;) And neither do you. I might have used you to create a massive email spam bomb. (I didn't, but you get the pointl

**Comment by fatalsaint** [comment] 2018-08-14 17:14
You are right, of course, using random Docker images is never a good idea but I had nothing critical in it and wanted to see it work :).

I am now using the mailu/postfix:master image with a postfix.cf in the overrides directory that statically sets the smtpd_authorized_xclient_hosts.

That seems to work as well.

**Closed** 2018-09-16 17:56 UTC
Labels: enhancement
