### ISSUE TITLE
Sorting and editing of aliases

### ISSUE THREAD

**Issue by trueserve** [Mailu/Mailu#155] opened 2017-01-25 05:14 UTC
First, to note: I have tested alias delivery where multiple alias rules can match, and it seems as if only the first matched rule is delivered. For example, if the first rule added is "test" is aliased to acct1, and the second rule is "te%" with SQL-Like enabled is to acct2, then a mail to "test" will only deliver to the first rule acct1, and not the second rule acct2. This behavior should be documented.

In my case, this is fine and is the behavior I want, but there is currently no way to sort the aliases from the web interface. If I need to make a change, then to sort them, I would need to delete them and re-enter them.

Additionally, the rule portion of the alias cannot be edited. It would make sense for this to be editable.

Is more extensive alias configuration going to be made available in the next release? If not, is sorting of aliases at least on the table as a feature?

**Comment by kaiyou** [comment] 2017-01-25 07:40
You are right, the behaviour should be documented. However, it is not this first alias that matches but the longest (and hopefully most specific). This behaviour was inspired by pattern matching in other applications and seems to be the norm.

What we could do however is sort them by decreasing length, what do you think?

**Comment by trueserve** [comment] 2017-01-25 15:08
Thank you for clarifying alias rule matching.

If the system already does this by length, then allowing editing of the alias and sorting them by length should be acceptable for the purpose of this ticket. I can't think of a negative to this.

Ultimately, either manual sorting (for the human desire for control and to visually separate alias targets), alias groups, or a view filter (to show only aliases to a relevant target for example) would be helpful.

**Comment by kaiyou** [comment] 2017-01-28 10:54
With single substitution characters, the most specific rule matches first, meaning that ``test`` matches before ``t?st``. I would have to check but it is the intended behaviour.

Problem with manual sorting is it makes no sense to prioritize ``t*`` over ``test``, as ``test`` will never match then ; the only edge case would be with non-inclusive patterns, like ``t?st`` and ``te?t``, but then is it really worth the time implementing the feature?

Maybe allow some sorting for displaying them, or dynamic search and sort fields. That could easily be implemented.

**Comment by trueserve** [comment] 2017-01-28 17:01
Re: sorting, yes, that would suffice. That, and allowing editing of rules, would make things much easier to work with right now.

Some future thinking thoughts and ideas follow:

Re: manual sorting, agreed that it makes little sense. It's really for the human aspect of control and possible ease of implementation. If the list is sorted to match the actual rule order I don't think it's necessary either.

Other things that would help are grouping or filtering rules for view. In my case, I have three "sets" of rules (for three classes of received data, with multiple addresses including pattern matching) so some way of differentiating them would be helpful. Maybe a 'description' or 'tag' field? I understand my needs here may be an edge case though.

Re: pattern edge case, it may eventually be an issue, I'm not worried about it now but just wanted to bring it up.

**Comment by kaiyou** [comment] 2017-02-02 20:30
Okay, editing alias localpart does not sound bad in the end. We will have to make sure that duplicates arent allowed though. I should implement this pretty soon.

**Comment by Nebukadneza** [comment] 2020-08-15 21:21
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment] 2020-09-25 09:33
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Closed by Diman0** 2020-09-25 09:33 UTC
Labels: status/response_needed, type/feature
