### ISSUE TITLE
DKIM missing when using identities in Rainloop

### ISSUE THREAD

**Issue by jlelse** [Mailu/Mailu#462] opened 2018-04-21 13:40 UTC
I have setup Mailu with multiple domains, but only have changed one domain's dns to my own server. The rest is still set to FastMail. The main mail domain I chose in the .env file isn't migrated yet.

Because I have multiple domains but only want one mailbox I set up catch-all alias for all domains to my only mailbox. That works so far.

However I also want to sent mails from addresses on the other domains, that's why I added identities in the Rainloop settings. But when testing with http://www.appmaildev.com/dkim, it says DKIM isn't set, although I added all the necessary DNS settings and also tried it with a subdomain on a different setup before. (So sending from the domain where the mailbox is works.)

And is it also possible to hide the smtp.auth with the original mail address from mail headers?

I'm considering switching to an own mail server from Fastmail, but that's currently holding me back.

**Comment by kaiyou** [comment] 2018-04-21 13:55
Well, first of all, did you generate dkim keys for all the domains you are sending emails from?

**Comment by jlelse** [comment] 2018-04-21 14:51
Yes I did. For the domain I try to send via the identity, I also added it to the DNS entries.

**Comment by dhain** [comment] 2018-05-03 13:11
This doesn't just affect Rainloop. I had the same problem sending from Apple Mail.

**Comment by kaiyou** [comment] 2018-05-03 17:56
Also, DKIM keys are per domain, so you will need to update your DNS entries

**Comment by dhain** [comment] 2018-05-03 20:14
Here's what I have. Two domains set up in Mailu: example1.com and example2.com. I have a real user set up as me@example1.com and an alias set up as me@example2.com pointing to the real user. Both domains have DKIM keys defined in Mailu and set up in DNS. If I send mail addressed from me@example2.com (while logging into SMTP as me@example1.com), the message is not signed. Sending mail addressed as a real user, eg. me@example1.com or otherrealuser@example2.com, works as intended.

**Comment by kaiyou** [comment] 2018-05-28 21:33
Okay, now I guess this is a bug. Probably a limitation of rspamd but it should be configurable.

**Comment by muhlemmer** [comment] 2018-12-05 23:20
Didn't auto-close after merge. Closing manually.

**Closed by muhlemmer** 2018-12-05 23:20 UTC
Labels: priority/p2, type/bug
