### ISSUE TITLE
Sent emails from alternate domains don't support DKIM signing

### ISSUE THREAD

**Issue by bolet** [Mailu/Mailu#1519] opened 2020-05-23 21:53 UTC
Additionaly I'd love headers sent from alternate domains to only mention the alternate domain, with no mention of the "original" domain. My use is for alternate domains to just merge incoming emails.

I know postfix allows that, but do we want this feature available in mailu ?

I'd be happy with a workaround. For instance, the admin UI blocks creating domains and alternates with similar names, but I haven't tested yet what happens if I just alter tables in the db.

**Comment by bolet** [comment] 2020-05-23 22:21
The workaround for sending is fine :
- in the admin UI
  - create domain1 and domain2
  - create DKIM for both domains
- add domain2 -> domain1 in the alternative table
- in the webmail
  - log with user@domain1
  - create identity user@domain2
  - send an email as user@domain2

Result : email is send and signed with DKIM from domain2

I still have to check if received emails for user@domain2 are received in user@domain1 mailbox.

**Comment by bolet** [comment] 2020-05-23 23:01
Hurray !!! With the above setup, emails received for user@domain2 are directed to user@domain1 as expected.

SO...

The feature is there, but the admin UI prevents "normal" users from accessing it. I'm risking some suggestions :

1. only allow domains that are already created and have no users to be added as alternatives (reverse the existing limitation),
2. prevent creation of users in domains that are used as alternatives to others,
3. prevent the same domain to be an alternative to more than one other.

**Comment by bolet** [comment] 2020-05-24 15:54
The following headers are missing when sending with domain1 :
- ARC-Message-Signature
- ARC-Seal
- ARC-Authentication-Results

How can we have the messages sent from domain2 also contain those headers?

**Comment by Aaron-Ritter** [comment] 2020-06-03 19:59
i guess it would be good while generating DKIM that it takes all alternative domains in to account?

**Comment by bolet** [comment] 2020-06-04 10:10
Following the procedure I describe, outgoing emails are sent from alternative domains are DKIM signed with the alternative domain key. But only those sent from the original domain also contain the ARC-* headers (which look similar but are not identical to DKIM signatures).

**Comment by Nebukadneza** [comment] 2020-08-16 09:21
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by GuillaumeOuint** [comment] 2020-11-30 00:55
Same here, and workaround doesn't work, I have to delete the domain for adding it on other domain alternative domain.
No stale please.

**Comment by bolet** [comment] 2020-12-18 01:17
> i guess it would be good while generating DKIM that it takes all alternative domains in to account?

If we want to have each domain (original and alternates) to have its own DKIM, it has to be displayed in the UI (so it can be copied to the DNS) and we should enable controls to remove or update the DKIM for each alternate domain.

I guess we could also sign all alternate domains with the original domain DKIM, but it feels wrong.

**Comment by waterside53** [comment] 2021-04-14 14:42
After struggling with the workaround here, I ended up with  just the one domain set up in the domain list and with domain2 as an alternative. In the dkim docker volume, I have the files domain1.dkim.key and domain2.dkim.key. This seems to be correctly signing messages sent with from addresses in either domain. The second of these was created when trying bolet's workaround but I imagine it could just be a copy of the key for domain1 using the same dkim._domainkey DNS entry for each domain.

**Comment by nextgens** [comment] 2021-11-10 14:21
Just to clarify: 

- what's the expected behaviour for ARC? IMHO you always want an ARC signature from a key linked to ``HOSTNAME`` (and not necessarily domain1 nor domain2)
- In a perfect world, how would it work UI wise? Should there be a separate entry in the left menu just for keys? (keeping in mind that there might be different keytypes #2050 or different versions/selectors #1700 for each domain)

**Comment by nextgens** [comment] 2021-11-10 14:23
Another point to consider is whether we want/should sign relayed emails from ``RELAYNETS`` (with ARC and maybe DKIM if we have keys)

**Comment by polenter** [comment] 2022-01-31 08:16
Thanks @bolet for the workaround. After many retries I have created a similar solution - with one exception - I don't create domain2, since when created - it won't be set as a domain alias/alternative for domain1.

During creating a domain alias, the Admin UI reports `Domain domain2 is already used`.

_add domain2 -> domain1 in the alternative table_

How did you do this? A command line, manual altering a configuration file, or the database?

There are over 2 years since the problem was reported and it seems to be still existing.

If I send an email using an alternate identity in the web client, based on an alias domain, the gmail server reports the following:

_Your message is not signed with DKIM_

If providing a DKIM to an email from an alias domain is not possible, it would be much of help, mentioning this in the docs.

**Comment by nextgens** [comment] 2022-01-31 08:38
@bolet if yoiu could answer https://github.com/Mailu/Mailu/issues/1519#issuecomment-965254724 it would help

I am fairly sure that you can already have DOMAIN1 and DOMAIN2 completely separate (stealth), as long as HOSTNAME derives from DOMAIN0 (is not from either).

Sending emails from DOMAIN1 or DOMAIN2 without having DOMAIN0 mentioned is not supported and probably not desirable (ARC signing with the DKIM key of the same domain makes less sense than ARC signing with a key what's used cross-domains).

**Comment by polenter** [comment] 2022-01-31 09:01
After some more retries, I have found a way, for attaching DKIM signature into an email, sent from a different domain, than the domain of the logged-in user.

The solution is based on user aliases, not on alternative domains.

The main user is `user1@domain1`, but the emails should be additionally sent as `user2@domain2`. The easiest way would be by the command line:

`docker-compose exec admin flask mailu alias user2 domain2 "user1@domain1"`

You can achieve this manually in the Admin UI as follows:
1. Create domains `domain1` and `domain2`
2. Generate keys for the domains
3. Create a real `user1` in the `domain1`
4. Create an alias `user2` in the `domain2` with the destination `user1@domain1`

The steps in the Webmailer UI are as in the workaround of @bolet (the second post in this thread):

5. Log-In as `user1@domain1` into Webmailer
6. Create additional identity `user2@domain2`
7. Send an email using the above identity

**Comment by nextgens** [comment] 2022-01-31 10:23
So this bug can be closed? or do you want to send a PR to document it?

**Comment by polenter** [comment] 2022-01-31 15:01
IMHO the bug is still there - an email sent from an alternative domain contains no DKIM signature. 
However defining a **catch all** alias for another domain has the same effect as defining this domain as an alternative domain, hasn't it?
If it's true - I would suggest updating the documentation (The paragraphs: alias and alternative domain) and closing the issue.

**Comment by Aaron-Ritter** [comment] 2022-01-31 15:14
I'd argue that creating an alternative domain should consequentially adjust the dkim and vice versa. Documenting the limitation and explaining manual workarounds is an interim step rather than a solution.

Especially as the admin interface should be something to avoid exactly such situations.

Basically what's the point of the admin interface to allow me setting up DKIM but not taking care of my alternative domains, or the other way around, let me setup alternative domains while not taking care of my already configured DKIM setup.

And the way DKIM is implemented and making our life easier in the current setup for the currently covered use case is great and i think we should, for the sake of further promiting DKIM, cover this "multi domain" use case as well.

Aaron

**Comment by Amunak** [comment] 2023-02-17 23:23
By the way if you ever get to this it'd be nice to also bake-in a way to customize the DKIM selectors and ideally also allow removing DKIM altogether (I'm not sure that's even possible at the moment).

I assume DKIM doesn't allow setting a key for the whole domain that'd apply to all subdomains too like with DMARC?

**Comment by Amunak** [comment] 2023-12-15 21:20
still very much an issue AFAIK.

**Comment by Aaron-Ritter** [comment] 2023-12-15 21:26
i agree, it's something which needs some love :)

**Comment by Jumper78** [comment] 2024-07-22 16:49
I tried the workaround described by @bolet (see https://github.com/Mailu/Mailu/issues/1519#issuecomment-633148058) but it did not work. Probably because there are some lines that prevent Rspamd from receiving a DKIM key if the domain is not in the list of main domains:
https://github.com/Mailu/Mailu/blob/d5bee885bfd5f965a3fd869cc60123f0ab660117/core/admin/mailu/internal/views/rspamd.py#L18-L19

In order to make DKIM work for my alternative domains, I added a couple of lines with an `elif` below the cited lines. You can find my solution in pull request #3350. If you want to try my solution, you can use the admin container with the label `pr-3350`:
```
image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:pr-3350
```

**Closed** 2024-08-11 16:50 UTC
Labels: type/enhancement
