### ISSUE TITLE
502 errors

### ISSUE THREAD

**Issue by CMclarty** [Mailu/Mailu#533] opened 2018-07-24 01:14 UTC
Have been trying a few different appraoches but nothing worked. I'm trying to get this integrated with an existing FQDM under a mailu.xxx.xxx address, but all I get is 502 errors. 

Ubuntu server 18.05

The docker images are fully up;

```
aa555fa5f49f        mailu/dovecot:1.5     "/bin/sh -c /start.py"   23 minutes ago      Up 23 minutes                                                         mailu_imap_1
e62ba99e9d81        mailu/rspamd:1.5      "/bin/sh -c /start.py"   23 minutes ago      Up 23 minutes                                                         mailu_antispam_1
4d524ed57eb7        mailu/postfix:1.5     "/bin/sh -c /start.py"   23 minutes ago      Up 23 minutes                                                         mailu_smtp_1
78d5af973c95        mailu/nginx:1.5       "/bin/sh -c /start.py"   23 minutes ago      Up 23 minutes       127.0.0.1:8080->80/tcp, 127.0.0.1:8443->443/tcp   mailu_front_1
a8436e91984c        mailu/fetchmail:1.5   "/fetchmail.py"          23 minutes ago      Up 23 minutes                                                         mailu_fetchmail_1
aee79371b3d9        mailu/admin:1.5       "/start.sh"              23 minutes ago      Up 23 minutes                                                         mailu_admin_1
82bcc7e0d6dc        mailu/none:1.5        "/bin/sh -c 'sleep 1…"   23 minutes ago      Up 23 minutes                                                         mailu_webdav_1
22b03fb75257        mailu/none:1.5        "/bin/sh -c 'sleep 1…"   23 minutes ago      Up 23 minutes                                                         mailu_antivirus_1
5ae99fa3cf4d        mailu/rainloop:1.5    "docker-php-entrypoi…"   24 minutes ago      Up 24 minutes       80/tcp                                            mailu_webmail_1
d9a1e7e0c00a        redis:alpine          "docker-entrypoint.s…"   2 hours ago         Up 2 hours          6379/tcp                                          mailu_redis_1
```

.env; 

```
ROOT=/srv/mailu/
VERSION=1.5
BIND_ADDRESS4=0.0.0.0
DOMAIN=xxx.xxx
HOSTNAMES=mailu.xxx.xxx
```

notls for testing purposes

compose.yml

(only things changed)

```
 front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    ports:
    - "127.0.0.1:8080:80"
    - "127.0.0.1:8443:443"
    volumes:
      - "$ROOT/certs:/certs"
```

and finally nginx conf;

```
server {
  listen 443;
  server_name mailu.callyverse.club;

  # [...] here goes your standard configuration

  location / {
    proxy_pass https://localhost:8443;
  }

 location /webmail {
    proxy_pass https://localhost:8443/webmail;
  }

  location /admin {
    proxy_pass https://127.0.0.1:8443/admin;
  }
}
```

It all seems like It should be playing along, but docker really isn't my forte. Where am I going wrong? Thanks for your help

**Comment by kaiyou** [comment] 2018-08-01 19:35
Is the nginx.conf from your local nginx server? If so, it is not the intended way for Mailu to run but it should run properly anyway.

Generally, I would say that forwarding ``/`` will suffice. Maybe the front container is not started properly or replying properly. Could you provide some detailed error messages?

**Comment by HorayNarea** [comment] 2018-11-02 22:35
> notls for testing purposes
>
> […]
> 
> ```
>     ports:
>     - "127.0.0.1:8080:80"
>     - "127.0.0.1:8443:443"
> ```
>
> […]
>
> ```
>   location / {
>     proxy_pass https://localhost:8443;
>   }
> ```

The problem is that @CMclarty is forwarding to mailu-nginx's HTTPS-port which it won't serve because you explicitly told it that you want `notls`.

You should either change the forwarding to 8080 or setup TLS in Mailu

**Comment by muhlemmer** [comment] 2018-12-05 23:17
No answer form the OP, original problem seems to be notls. 502 troubleshooting is recently committed to the FAQ. Closing this.

**Closed by muhlemmer** 2018-12-05 23:17 UTC
Labels: faq/done, faq/troubleshooting, status/notabug, topic/core
