### ISSUE TITLE
Error Creating DH params in latest

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#268] opened 2017-09-18 14:45 UTC
All appeared to work with the new test domain with traefik and rainloop.

TLS is set to cert.

```
root@mail:/mailu# docker-compose run --rm admin python manage.py admin root example.net password
Creating DH params
Job "create_dhparam (trigger: date[2017-09-18 14:40:20 UTC], next run at: 2017-09-18 14:40:20 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/mailu/tlstasks.py", line 53, in create_dhparam
    subprocess.call(["openssl", "dhparam", "-out", dhparam_path, "2048"])
  File "/usr/local/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'openssl'
```

**Comment by kaiyou** [comment] 2017-09-18 19:34
Indeed, `openssl` was mistakenly removed from the `latest` admin container for a couple hours recently. This was fixed though, I believe. Could you try and pull the latest admin container?

**Comment by kaiyou** [comment] 2017-09-18 19:35
My bad, I can reproduce this. I will check what happened to building the admin container.

**Comment by kaiyou** [comment] 2017-09-18 19:39
Fixed by e14f93d4291b96273773ddad457b94efc8f3f387, build is in progress

**Comment by SaiGonSeamus** [comment] 2017-09-18 20:21
OK, that worked but with one error.

```
root@mail:/mailu# docker-compose run --rm admin python manage.py admin root example.net password
Creating DH params
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
......................................................................................................Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 178, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 20, in admin
    db.session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
.    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email [SQL: 'INSERT INTO user (created_at, updated_at, comment, localpart, password, quota_bytes, global_admin, enable_imap, enable_pop, forward_enabled, forward_destination, forward_keep, reply_enabled, reply_subject, reply_body, displayed_name, spam_enabled, spam_threshold, domain_name, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2017-09-18', None, None, 'root', '{SHA512-CRYPT}$6$rounds=656000$AuGONjf66mheduhK$liXyWFZaOek3aupuOTqFsk7aNOcvRta.LMnWKUh87b/xlLxp4686rhb1t2yTJ9lhG.h7t89IETy/AOx1A/nkx0', 1000000000, 1, 1, 1, 0, None, 1, 0, None, None, '', 1, 80.0, 'example.net', 'root@example.net')]
.........................................+.......................................................+.............+....................................................................................+..............................................................+......................................................+..........................................+............................................................................................................................................................................................+..........................................................................................................................................+..................................................................................................+...........+.........................................................................................................................................................................................................................................+........................................................................................................................................................................................................................................................................................................................................................................................................................................................................+..................................................................................................................+......................................................................................................................................................................................+...........................................................................................................................................................................+..............................................................................................................................................................................................................................................................................+......................................................................................................................................................................................+........................................................................+................................+..................................................................................................................................................++*++*
```

**Comment by kaiyou** [comment] 2017-09-18 20:39
Well, this is simply because the user already exists I believe :)

**Closed** 2017-09-18 20:40 UTC
Labels: bug
