### ISSUE TITLE
Switch from SQLite - Mandatory for most k8s installs

### ISSUE THREAD

**Issue by iMartyn** [Mailu/Mailu#569] opened 2018-08-13 15:14 UTC
I know this is already in your mind, but here is the problem :

- Kubernetes supports very few "shared volumes" that work in multi-node clusters and all of them are somewhat nfs-based.
  - nfs autoprovisioner
  - glusterfs
  - rook.io has a shared mode I haven't tried
- SQLite breaks significantly with nfs, and very easily with multiple users accessing it (as is the setup used in mailu) See https://stackoverflow.com/questions/29244788/error-disk-i-o-error-on-a-newly-created-database, https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible and https://stackoverflow.com/questions/5043327/how-to-ensure-a-safe-file-sync-with-sqlite-and-nfs

So basically if you want to run umail on k8s (which I do) you are restricted to running everything on one node and hostpath.

For completeness, here is a log from my setup that was working a few hours ago and "just stopped" :
```
100.64.0.37 - - [13/Aug/2018:15:09:11 +0000] "GET /internal/auth/email HTTP/1.0" 500 291 "-" "-"
[2018-08-13 15:09:11,435] ERROR in app: Exception on /internal/auth/email [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 544, in __inner
    return obj(*a, **k)
  File "/app/mailu/internal/views.py", line 18, in nginx_authentication
    headers = nginx.handle_authentication(flask.request.headers)
  File "/app/mailu/internal/nginx.py", line 40, in handle_authentication
    user = models.User.query.get(user_email)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 882, in get
    ident, loading.load_on_ident)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 916, in _get_impl
    return fallback_fn(self, key)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 232, in load_on_ident
    return q.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2848, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2818, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: 'SELECT user.created_at AS user_created_at, user.updated_at AS user_updated_at, user.comment AS user_comment, user.localpart AS user_localpart, user.password AS user_password, user.quota_bytes AS user_quota_bytes, user.global_admin AS user_global_admin, user.enabled AS user_enabled, user.enable_imap AS user_enable_imap, user.enable_pop AS user_enable_pop, user.forward_enabled AS user_forward_enabled, user.forward_destination AS user_forward_destination, user.forward_keep AS user_forward_keep, user.reply_enabled AS user_reply_enabled, user.reply_subject AS user_reply_subject, user.reply_body AS user_reply_body, user.reply_enddate AS user_reply_enddate, user.displayed_name AS user_displayed_name, user.spam_enabled AS user_spam_enabled, user.spam_threshold AS user_spam_threshold, user.domain_name AS user_domain_name, user.email AS user_email \nFROM user \nWHERE user.email = ?'] [parameters: ('my@email.addr',)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by christhomas** [comment] 2018-08-26 14:11
With my VPS installed and configured postfix setup, I used mysql for what mailu is using sqlite for, I guess that is a viable solution if you've already got the infrastructure setup for mysql. Thanks for pointing this out, it'll save my valuable debugging time, I'll just rip that bit out and replace it.

**Comment by kaiyou** [comment] 2018-09-16 18:45
This is indeed kind of a duplicate of #420, which is going pretty well, since my feature branch is almost working. Need more time testing and we can support other database backends :) Closing here.

**Closed by kaiyou** 2018-09-16 18:45 UTC
