### ISSUE TITLE
plus mail in auto-forward destination

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#1236] opened 2019-11-03 17:52 UTC
The email address in `admin -> User settings -> Auto-forward -> Destination` cannot contains a '+' character (error: Invalid email address). But the '+' in email address is valid and admin should accept it.

**Comment by kaiyou** [comment] 2019-11-04 18:09
This is a pretty straightforward bug probably related to flask form validation

**Comment by Nebukadneza** [comment] 2020-08-16 11:07
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment] 2021-12-14 10:44
The problem is probably here:
https://github.com/Mailu/Mailu/blob/dbbfa44461c3b8a537e9fe6b56f4690417d3c8a2/core/admin/mailu/ui/forms.py#L40
This is the validator for the forward field
https://github.com/Mailu/Mailu/blob/dbbfa44461c3b8a537e9fe6b56f4690417d3c8a2/core/admin/mailu/ui/forms.py#L106

I think it can be fixed with this regex
```^([+_a-z0-9\-]+)(\.[+_a-z0-9\-]+)*@([a-z0-9\-]{2,}\.)*([a-z]{2,})(,([+_a-z0-9\-]+)(\.[+_a-z0-9\-]+)*@([a-z0-9\-]{2,}\.)*([a-z]{2,}))*$```
According to https://regex101.com/ the regex works.

**Closed** 2023-02-06 12:22 UTC
Labels: priority/p2, type/bug, backlog
