### ISSUE TITLE
E-mail folder is not deleted when the account is deleted

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#193] opened 2017-04-17 14:03 UTC
When an e-mail account is deleted, its mail folder remains in the filesystem. If you recreate the account, the mail data can be read again by the user with the same name. Although this can be useful when the user is mistakenly deleted, I think we should have a procedure to delete stale data. 

I think the best option would be to set a cron job to delete data periodically, so we remain with the ability to recreate the user when it is mistakenly deleted, but we have a garbage collector to shrink the size of the mail folder.

**Comment by kaiyou** [comment] 2017-05-04 17:05
That is indeed an unexpected and unwanted behavior. I agree with using a CRON job. I would however prefer to have a status bit like "set for deletion" set when the admin decides to delete an account, and have the CRON job actually delete the entry once data is erased.

Also nice to have: a secure delete option.

**Comment by HorayNarea** [comment] 2017-11-12 03:08
if this will be implemented, please add a warning if a user with the same name is added as long as the old data still exists, so that an adminstrator can re-add the old user if it was accidentally deleted but only if that's really what they want

**Comment by kaiyou** [comment] 2017-11-12 10:45
Yes. I am still unsure how we should proceed with this. I mean I would prefer the admin container not access the maildirs directly. Should we have a separate container handle garbage collection?

**Comment by HorayNarea** [comment] 2017-11-12 11:26
Hmm… Maybe we could add a `markedforDeletion`-field to the DB and a seperate container runs a periodic GC?
That way the admin-container could look at that field to show a warning and only ever touch the DB

**Comment by HorayNarea** [comment] 2017-11-12 11:28
The UI could then also say something like `mark this account for deletion (can be undone before next GC-run, which is in: $duration)`

**Comment by HorayNarea** [comment] 2017-11-17 07:30
Another idea: using autoexpunge on the INBOX-configuration https://wiki.dovecot.org/MailboxSettings, if I understand it correct that would delete the maildir-contents after the set duration of a user not logging in

So if one deletes a user from the database and `autoexpunge=30d` is set, 30 days later the mails will be deleted

**Comment by muhlemmer** [comment] 2018-10-12 09:48
Before I came to Mailu, I was busy setting up [postfixadmin](https://github.com/postfixadmin/postfixadmin). What I remember from that setup, they move the user mail folder to a "deleted" location. (Like a trash bin).

We could implement something like that by running a simple operation like:
```
mv /mailu/mail/user@domain.com /mailu/mail/user@domain.com-deleted
```

Undelete will be just a matter of moving back. A simple cron job can take care of cleaning `*-deleted` entries (to the admin's taste)

**Comment by kaiyou** [comment] 2020-02-07 14:55
Duplicate of #970

**Closed by kaiyou** 2020-02-07 14:55 UTC
Labels: priority/p2, type/enhancement

**Comment by redispade** [comment] 2022-03-31 11:08
Any news on this?
