### ISSUE TITLE
Rspamd web ui

### ISSUE THREAD

**Issue by darkermatter** [Mailu/Mailu#244] opened 2017-08-29 18:03 UTC
Hello,

is there a way to access the Rspamd web ui?

Thanks!

**Comment by kaiyou** [comment] 2017-09-03 12:15
There is none for know, I guess it could be exposed behind the reverse proxy, but we would need a proper way to authenticate the admin.

**Comment by kaiyou** [comment] 2017-09-10 17:18
Actually this is a duplicate of #157, let's move over there for discussions :)

**Closed by kaiyou** 2017-09-10 17:18 UTC
Labels: feature
