### ISSUE TITLE
Rainloop: Cannot search mail, error "Can't get message list"

### ISSUE THREAD

**Issue by trueserve** [Mailu/Mailu#701] opened 2018-11-02 17:44 UTC
In `master`, some time within the last few months, I have not been able to reliably search my mail. Sometimes it works, but it usually results in a red `Can't get message list` error. It did work before.

Mailbox has less than 5000 mails, shouldn't be a size issue.

Looking at Rainloop related bugs, I have seen this but it reflected abnormally large inboxes with long search times or other since-fixed bugs.

Any idea where to start with this?

**Comment by HorayNarea** [comment] 2018-11-02 21:06
Is there anything interesting in the webmail-container logs?

**Comment by trueserve** [comment] 2018-11-23 02:53
Sorry, just getting around to this reply.

No, all I see are GET/POST but no errors via `docker logs` but no errors. Perhaps you could point me to where to look?

My dovecot logs show the following though:

```Nov 22 19:51:17 imap-login: Info: Login: user=<acct@example.com>, method=PLAIN, rip=172.19.0.3, lip=172.19.0.9, mpid=638, session=<RpWmDkx7Cr+sEwAD>
Nov 22 19:51:17 imap(acct@example.com)<638><RpWmDkx7Cr+sEwAD>: Info: Logged out in=89 out=991 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Nov 22 19:51:17 imap(acct@example.com)<637><AISmDkx7CL+sEwAD>: Info: Logged out in=55 out=1007 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Nov 22 19:51:17 imap(acct@example.com)<636><qV2mDkx7BL+sEwAD>: Info: Logged out in=80 out=3763 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Nov 22 19:51:21 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<9dTkDkx7eYx/AAAB>
```

The IMAP connections close quickly after connecting. Not sure what the pop3 connection attempts are for...

**Comment by trueserve** [comment] 2018-11-23 03:14
If I set the messages on page to 10, I can usually get searches to work. I feel this is likely more a Rainloop issue but I don't see the bug resolved over there.

**Comment by muhlemmer** [comment] 2018-12-18 21:16
Do you have any errors in the logs of IMAP? By any change something like #751?

**Comment by hoellen** [comment] 2018-12-27 09:05
I'm getting the following in the log: 
```
imap_1       | Dec 27 08:54:29 imap(user@domain.tld)<157><mcEqSP19dpnAfMsD>: Fatal: master: service(imap): child 157 killed with signal 11 (core not dumped - https://dovecot.org/bugreport.html#coredumps - set /proc/sys/fs/suid_dumpable to 2)
```
Before that I mostly got the error-log from #751 (index-worker killed). But since the workaround this doesn't happens anymore. Now the log from above is coming.

**Comment by muhlemmer** [comment] 2018-12-31 01:33
@hoellen: and rainloop still can't get the message list? With me it started to work after the workaround was in place.

It might be that the remaining error is a separate bug altogether which needs debugging...

**Comment by hoellen** [comment] 2018-12-31 07:42
@muhlemmer It started to work for the most users when disabling luscene. But there is still a user complaining about the message list error. In the logs then there is the error message from above. 

I unfortunately also believe that this is another bug...

**Comment by muhlemmer** [comment] 2019-01-04 10:38
@hoellen. I'm unable to reproduce... I've created a python script which is bombing my mailbox will e-mail. With the workaround in place, I'm doing searches, have multiple clients (webmail and thunderbird) simultaneously logged in, moving messages, deleting them and bulk "mark as read" while I'm bombing the test server with new mails!

Are you sure you cleaned up the corrupted index files as suggested in #751?

**Comment by hoellen** [comment] 2019-01-07 08:37
I was just digging into it and now I've seen that I had a typo in `DISABLE_FTS_LUCENE`, so it was not disabled. Mea culpa, sorry for that. It works like a charm now.

**Comment by muhlemmer** [comment] 2019-01-07 10:46
Ok, that's a relieve. I'll close this in favor of #751 (that one has the most up-to-date info)

**Closed by muhlemmer** 2019-01-07 10:46 UTC
Labels: type/bug
