### ISSUE TITLE
mail-front isn't listening to port 25

### ISSUE THREAD

**Issue by karimhm** [Mailu/Mailu#1146] opened 2019-08-29 09:34 UTC
mail-front isn't listening on port 25

But everything else work perfectly.

My configuration is as follow:

    front:
    image: mailu/nginx:1.6
    container_name: "mail-front"
    restart: always
    env_file: mail.env
    logging:
      driver: json-file
    ports:
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
    volumes:
      - /var/lib/docker-containers/containers-data/mail/ngnix:/overrides
      - /var/lib/docker-containers/containers-data/mail/overrides:/overrides"
      - /var/lib/docker-containers/containers-data/mail/certs:/certs
    networks:
      - mail
    depends_on:
      - admin
    labels:
      - traefik.frontend.rule=Host:mail.{MY_DOMAIN}.com
      - traefik.docker.network=mail
      - traefik.port=80
      - traefik.enable=true
    
    smtp:
    image: mailu/postfix:1.6
    container_name: "postfix"
    restart: always
    env_file: mail.env
    volumes:
      - /var/lib/docker-containers/containers-data/mail/overrides:/overrides
    depends_on:
      - front
    networks:
      - mail
    labels:
      - traefik.enable=false

When running **netstat -plnt** i get:

    tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      722/systemd-resolve 
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      21133/sshd          
    tcp6       0      0 :::32778                :::*                    LISTEN      11329/docker-proxy  
    tcp6       0      0 :::587                  :::*                    LISTEN      11281/docker-proxy  
    tcp6       0      0 :::110                  :::*                    LISTEN      11317/docker-proxy  
    tcp6       0      0 :::143                  :::*                    LISTEN      11305/docker-proxy  
    tcp6       0      0 :::465                  :::*                    LISTEN      11293/docker-proxy  
    tcp6       0      0 :::22                   :::*                    LISTEN      21133/sshd          
    tcp6       0      0 :::993                  :::*                    LISTEN      11269/docker-proxy  
    tcp6       0      0 :::995                  :::*                    LISTEN      11256/docker-proxy

When running **docker ps** i get:

    1d24ea59e5bb        mailu/postfix:1.6                     "/bin/sh -c /start.py"   3 hours ago         Up 3 hours (healthy)   25/tcp, 10025/tcp                                                                                                                                                                                           

    9047fb8b168b        mailu/dovecot:latest                  "/bin/sh -c /start.py"   3 hours ago         Up 3 hours (healthy)   110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp  

    81905d765211        mailu/nginx:1.6                       "/bin/sh -c /start.py"   3 hours ago         Up 3 hours (healthy)   25/tcp, 0.0.0.0:110->110/tcp, 80/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:587->587/tcp, 0.0.0.0:993->993/tcp, 443/tcp, 10025/tcp, 10143/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:32778->1525/tcp   mail-front

**Comment by kaiyou** [comment] 2019-08-29 16:06
Just so you know: we just branched 1.7, so I would recommend it for a new setup.

From the docker ps it really looks like the port spec is not setup by Docker at all. Could you post a docker inspect of your front container?

**Comment by karimhm** [comment] 2019-08-29 20:32
Thanks for your reply,

running **docker inspect** on mail-front give this:

    [
    {
        "Id": "81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df",
        "Created": "2019-08-29T06:02:12.294095489Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/start.py"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 11362,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-29T06:02:14.349846153Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-08-29T20:25:25.111697007Z",
                        "End": "2019-08-29T20:25:25.486882118Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    },
                    {
                        "Start": "2019-08-29T20:25:55.490561055Z",
                        "End": "2019-08-29T20:25:55.901403846Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    },
                    {
                        "Start": "2019-08-29T20:26:25.905222072Z",
                        "End": "2019-08-29T20:26:26.365197969Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    },
                    {
                        "Start": "2019-08-29T20:26:56.369326045Z",
                        "End": "2019-08-29T20:26:56.724185397Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    },
                    {
                        "Start": "2019-08-29T20:27:26.730210984Z",
                        "End": "2019-08-29T20:27:27.45207523Z",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    }
                ]
            }
        },
        "Image": "sha256:d712c4b3fca75ddd8de50b5838099c4722687b9d983ccc8070f2d678643e135e",
        "ResolvConfPath": "/var/lib/docker/containers/81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df/hostname",
        "HostsPath": "/var/lib/docker/containers/81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df/hosts",
        "LogPath": "/var/lib/docker/containers/81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df/81905d765211cb7a53e998483d32cf51534a80548035d7d9ccf1b4d93e1999df-json.log",
        "Name": "/mail-front",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/lib/docker-containers/containers-data/mail/overrides:/overrides\":rw",
                "/var/lib/docker-containers/containers-data/mail/certs:/certs:rw",
                "/var/lib/docker-containers/containers-data/mail/ngnix:/overrides:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "mail",
            "PortBindings": {
                "110/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "110"
                    }
                ],
                "143/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "143"
                    }
                ],
                "1525/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ],
                "465/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "465"
                    }
                ],
                "587/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "587"
                    }
                ],
                "993/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "993"
                    }
                ],
                "995/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "995"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/0490d516dd65572f497a9a2b205dd703f7e3531693e3751360e78f785171791d-init/diff:/var/lib/docker/overlay2/2b1ef84ab905bccdc685874bbbafae9007286e8a07a3566524d09258f3d7347b/diff:/var/lib/docker/overlay2/5008d47a7138ead5e71b0d1bce0cbe692ab6c0182e738a5f0120584cac2c5e9c/diff:/var/lib/docker/overlay2/ded0c630850c6a31193f77504eccbc9403ec2565453f00a023bd9ea9baa127e4/diff:/var/lib/docker/overlay2/b81b1ec7915f18c3c421bf2e10cfc589faf91656ba2ebd39e5e18ddc3e563965/diff:/var/lib/docker/overlay2/9fe8d19eef14ee3cd6c812d10f55989d227f435188f9d775948a24326eca2a5c/diff:/var/lib/docker/overlay2/495e2e8412f948c13d79b99e3973e98648e6d1e4fb58e8ea5d0840bd08b26f20/diff:/var/lib/docker/overlay2/5cbdbdf3dec4d5610ec898e136a49f5a405ea32d960c6b37e8137b4c5e234013/diff",
                "MergedDir": "/var/lib/docker/overlay2/0490d516dd65572f497a9a2b205dd703f7e3531693e3751360e78f785171791d/merged",
                "UpperDir": "/var/lib/docker/overlay2/0490d516dd65572f497a9a2b205dd703f7e3531693e3751360e78f785171791d/diff",
                "WorkDir": "/var/lib/docker/overlay2/0490d516dd65572f497a9a2b205dd703f7e3531693e3751360e78f785171791d/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/docker-containers/containers-data/mail/overrides",
                "Destination": "/overrides\"",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rslave"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/docker-containers/containers-data/mail/certs",
                "Destination": "/certs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rslave"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/docker-containers/containers-data/mail/ngnix",
                "Destination": "/overrides",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rslave"
            }
        ],
        "Config": {
            "Hostname": "81905d765211",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10025/tcp": {},
                "10143/tcp": {},
                "110/tcp": {},
                "143/tcp": {},
                "1525/tcp": {},
                "25/tcp": {},
                "443/tcp": {},
                "465/tcp": {},
                "587/tcp": {},
                "80/tcp": {},
                "993/tcp": {},
                "995/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ROOT=/var/lib/docker-containers/containers-data/mail",
                "VERSION=1.6",
                "SECRET_KEY=9CKTCMIGBO0GA1RX",
                "SUBNET=10.10.200.0/24",
                "DOMAIN={}.com",
                "HOSTNAMES={MY_DOMAIN}.com,mail.{MY_DOMAIN}.com",
                "POSTMASTER=admin",
                "TLS_FLAVOR=mail",
                "AUTH_RATELIMIT=10/minute;1000/hour",
                "DISABLE_STATISTICS=True",
                "ADMIN=true",
                "WEBMAIL=roundcube",
                "WEBDAV=radicale",
                "ANTIVIRUS=none",
                "ANTISPAM=",
                "MESSAGE_SIZE_LIMIT=50000000",
                "RELAYNETS=",
                "RELAYHOST=",
                "FETCHMAIL_DELAY=600",
                "RECIPIENT_DELIMITER=+",
                "DMARC_RUA=admin",
                "DMARC_RUF=admin",
                "WELCOME=false",
                "WELCOME_SUBJECT=Welcome to your new email account",
                "WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!",
                "COMPRESSION=",
                "COMPRESSION_LEVEL=",
                "WEBROOT_REDIRECT=/admin",
                "WEB_ADMIN=/admin",
                "WEB_WEBMAIL=/mail",
                "SITENAME=Karim Mail",
                "WEBSITE=https://{MY_DOMAIN}.com",
                "COMPOSE_PROJECT_NAME=mail",
                "PASSWORD_SCHEME=BLF-CRYPT",
                "REAL_IP_HEADER=",
                "REAL_IP_FROM=",
                "REJECT_UNLISTED_RECIPIENT=",
                "LOG_LEVEL=INFO",
                "TRAEFIK_DOMAIN={MY_DOMAIN}.com",
                "DB_FLAVOR=sqlite",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/start.py"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -k -f -L http://localhost/health || exit 1"
                ]
            },
            "Image": "mailu/nginx:1.6",
            "Volumes": {
                "/certs": {},
                "/overrides": {},
                "/overrides\"": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "ea5a1b97d441de0bef6fd738d290d17d102d3985c913098d57dd2fe6591a1827",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "mail",
                "com.docker.compose.service": "front",
                "com.docker.compose.version": "1.22.0",
                "traefik.docker.network": "mail",
                "traefik.enable": "true",
                "traefik.frontend.rule": "Host:mail.{MY_DOMAIN}.com",
                "traefik.port": "80"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3a94f322372b4eb7ed79ffcb218e252a52129614d6bf7be5acee934a6ee3af3c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "10025/tcp": null,
                "10143/tcp": null,
                "110/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "110"
                    }
                ],
                "143/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "143"
                    }
                ],
                "1525/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32778"
                    }
                ],
                "25/tcp": null,
                "443/tcp": null,
                "465/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "465"
                    }
                ],
                "587/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "587"
                    }
                ],
                "80/tcp": null,
                "993/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "993"
                    }
                ],
                "995/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "995"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/3a94f322372b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "mail": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "front",
                        "81905d765211"
                    ],
                    "NetworkID": "78a0c0841c4f40b1f164ed89d71cf504aa46292bee17be3e34e0871375ca2330",
                    "EndpointID": "62264c93ac5bb65600ac7c7d70fbd7977c169b788d45f17d4739e38b7d3bfa41",
                    "Gateway": "10.10.200.1",
                    "IPAddress": "10.10.200.7",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:0a:c8:07",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by kaiyou** [comment] 2019-08-29 21:11
Your container settings does not have port 25, so that would explain. Could you first try to down then up the entire stack?

Then, is there any specific error messages fron compose or Docker when you up the stack? Could you maybe paste your compose.yml somewhere we can get the original (like pastebin) for testing and comparing the results?

**Comment by karimhm** [comment] 2019-08-29 21:41
> Your container settings does not have port 25, so that would explain. Could you first try to down then up the entire stack?

I tried down and up again and tried installing version 1.7 and latest, but didnt work

> Then, is there any specific error messages fron compose or Docker when you up the stack? Could you maybe paste your compose.yml somewhere we can get the original (like pastebin) for testing and comparing the results?

i didn't get any error message,

Running **netstat** inside smtp (postfix) give this:

    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:10025           0.0.0.0:*               LISTEN      -
    tcp        0      0 127.0.0.11:34807        0.0.0.0:*               LISTEN      -
    tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      -
    tcp        0      0 :::10025                :::*                    LISTEN      -
    tcp        0      0 :::25                   :::*                    LISTEN      -
    udp        0      0 127.0.0.11:45491        0.0.0.0:*                           -

i have 2 docker stacks 

one for mail:

    version: '3.6'

    services:
      redis:
        image: redis:alpine
        container_name: "mail-redis"
        restart: always
        volumes:
          - /var/lib/docker-containers/containers-data/mail/redis:/data
        networks:
          - mail
        labels:
          - traefik.enable=false

      front:
        image: mailu/nginx:1.7
        container_name: "mail-front"
        restart: always
        env_file: mail.env
        logging:
          driver: json-file
        ports:
          - 25:25
          - 465:465
          - 587:587
          - 110:110
          - 995:995
          - 143:143
          - 993:993
        volumes:
          - /var/lib/docker-containers/containers-data/mail/ngnix:/overrides
          - /var/lib/docker-containers/containers-data/mail/overrides:/overrides"
          - /var/lib/docker-containers/containers-data/mail/certs:/certs
        networks:
          - mail
        depends_on:
          - admin
        labels:
          - traefik.frontend.rule=Host:mail.karhm.com
          - traefik.docker.network=mail
          - traefik.port=80
          - traefik.enable=true

      admin:
        image: mailu/admin:1.7
        container_name: "mail-admin"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/admin/data:/data
          - /var/lib/docker-containers/containers-data/mail/dkim:/dkim
        depends_on:
          - redis
        networks:
          - mail
        labels:
          - traefik.enable=false

      smtp:
        image: mailu/postfix:1.7
        container_name: "postfix"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/overrides:/overrides
        depends_on:
          - front
        networks:
          - mail
        labels:
          - traefik.enable=false

      imap:
        image: mailu/dovecot:latest
        container_name: "dovecot"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/dovecot/mail:/mail
          - /var/lib/docker-containers/containers-data/mail/overrides:/overrides
        depends_on:
          - front
        networks:
          - mail
        labels:
          - traefik.enable=false

      webmail:
        image: mailu/roundcube:1.7
        container_name: "roundcube"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/webmail:/data
        depends_on:
          - imap
        networks:
          - mail
        labels:
          - traefik.enable=false

      webdav:
        image: mailu/radicale:1.7
        container_name: "webdav"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/dav:/data
        networks:
          - mail

      antispam:
        image: mailu/rspamd:1.7
        container_name: "rspamd"
        restart: always
        env_file: mail.env
        volumes:
          - /var/lib/docker-containers/containers-data/mail/filter:/var/lib/rspamd
          - /var/lib/docker-containers/containers-data/mail/dkim:/dkim
          - /var/lib/docker-containers/containers-data/mail/overrides/rspamd:/etc/rspamd/override.d
        depends_on:
          - front
        networks:
          - mail
        labels:
          - traefik.enable=false

      certdumper:
        image: mailu/traefik-certdumper:1.7
        container_name: "cert-dumper"
        environment:
          - DOMAIN=*.karhm.com
          - TRAEFIK_DOMAIN=*.karhm.com
        volumes:
          - /var/lib/docker-containers/containers-data/traefik:/traefik
          - /var/lib/docker-containers/containers-data/mail/certs:/output
        networks:
          - mail
        labels:
          - traefik.enable=false

      z-push:
        image: karhm/z-push
        container_name: "z-push"
        restart: always
        environment:
          - Z_PUSH_IMAP_SERVER=imap
        depends_on:
          - imap
          - front
        networks:
          - mail
        labels:
          - traefik.frontend.rule=Host:karhm.com
          - traefik.frontend.rule=PathPrefix:/Microsoft-Server-ActiveSync;
          - traefik.docker.network=mail
          - traefik.port=80
          - traefik.enable=true

      autodiscover:
        image: weboaks/autodiscover-email-settings
        container_name: "autodiscover"
        restart: always
        environment:
          - DOMAIN=karhm.com
          - IMAP_HOST=karhm.com
          - IMAP_PORT=993
          - SMTP_HOST=karhm.com
          - SMTP_PORT=465
        networks:
          - mail
        labels:
          - traefik.frontend.rule=Host:autodiscover.karhm.com
          - traefik.docker.network=mail
          - traefik.port=8000
          - traefik.enable=true

    networks:
      mail:
        name: "mail"
        ipam:
          config:
            - subnet: 10.10.200.0/24

and one for traefik:

    version: '3.6'

    services:
      traefik:
        image: traefik:alpine
        container_name: traefik
        command:  --docker
        restart: always
        ports:
          - 80:80     # HTTP port
          - 443:443   # HTTPS port
        environment:
          - AWS_ACCESS_KEY_ID=
          - AWS_SECRET_ACCESS_KEY=
          - AWS_HOSTED_ZONE_ID=
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
          - /var/lib/docker-containers/stacks/web/traefik/traefik.toml:/traefik.toml
          - /var/lib/docker-containers/containers-data/traefik/acme.json:/acme.json
          - /var/lib/docker-containers/containers-data/traefik/traefik.log:/traefik.log
        networks:
          - web
          - mail
        labels:
          - traefik.enable=false

    networks:
      web:
        name: "web"

      mail:
        external: true

**Comment by karimhm** [comment] 2019-08-30 23:47
When i change the port 25 binding from this:

    ports:
      - 25:25

To this:

    ports:
      - "0.0.0.0:25:25"

Everything work fine, and the result of running docker ps is:

    4e882038e0c9        mailu/nginx:1.7                       "/bin/sh -c /start.py"   About an hour ago   Up About an hour (healthy)   0.0.0.0:25->25/tcp, 0.0.0.0:110->110/tcp, 80/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:587->587/tcp, 0.0.0.0:993->993/tcp, 443/tcp, 10025/tcp, 0.0.0.0:995->995/tcp, 10143/tcp   mail-front

**Comment by kaiyou** [comment] 2019-08-31 08:35
It does sound like you found a bug in Compose or Docker. I will try to reproduce locally.

**Comment by Heziode** [comment] 2020-01-15 21:49
> When i change the port 25 binding from this:
> 
> ```
> ports:
>   - 25:25
> ```
> 
> To this:
> 
> ```
> ports:
>   - "0.0.0.0:25:25"
> ```
> 
> Everything work fine, and the result of running **docker ps** is:
> 
> ```
> 4e882038e0c9        mailu/nginx:1.7                       "/bin/sh -c /start.py"   About an hour ago   Up About an hour (healthy)   0.0.0.0:25->25/tcp, 0.0.0.0:110->110/tcp, 80/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:587->587/tcp, 0.0.0.0:993->993/tcp, 443/tcp, 10025/tcp, 0.0.0.0:995->995/tcp, 10143/tcp   mail-front
> ```

I confirm that with `0.0.0.0:25:25` but `25:25` not.
I'm behind a treafik v2 RP. All traefik (HTTP/HTTPS and TCP) are managed by traefik.

**Comment by Nebukadneza** [comment] 2020-03-07 19:21
Hi,

I just tried this real quick with a few recent~ish compose versions, and one rather old. Indeed the old one (1.19.0) exhibited this behavior.

Would you be okay with closing this, if it doesn’t come up for recent compose versions on your systems anymore?

**Comment by Heziode** [comment] 2020-03-08 09:32
@Nebukadneza take a look on [my reply on an other issue](https://github.com/Mailu/Mailu/issues/1370#issuecomment-596000172).

With traefik V2, when I set `0.0.0.0:25:25` in traefik port conf, my mail server become an open-relay. We should use `<server IP>:25:25` instead.

**Comment by Nebukadneza** [comment] 2020-08-15 21:33
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Closed** 2020-09-24 10:04 UTC
Labels: status/response_needed
