### ISSUE TITLE
Keep fetchmail storage in a volume

### ISSUE THREAD

**Issue by RobertMe** [Mailu/Mailu#1283] opened 2019-12-13 16:30 UTC
Hi,
I'm investigating to use Mailu instead of a self hosted/maintained mail solution. I'm currently using fetchmail in combination with the `keep` option and I would like to keep doing so. And I've seen that setting the keep option is also possible in mailu so that's nice. But I noticed that the `.fetchids` files is kept in `/home/fetchmail/`. And as this file maintains a list of mails already fetched/imported it is thus very important that this file is stored in a persistent location. In other words, it must be kept in a volume. Otherwise recreating the container (like in an upgrade) will obviously mean that the file is lost and Fetchmail wil thus download every single mail again.

So I believe there is a bug with the following steps to reproduce:
1. From the admin panel configure Fetchmail and enable the "Keep mails on server" option.
2. Let fetchmail do its thing (ie: download mails from a server)
3. Remove the fetchmail container, and create a new one

The expected result is obviously that nothing happens. But I think that all mails will be fetched again. Because Fetchmail lost the `.fetchids` file and thus doesn't know it already downloaded those mails.

I know that I can manually set a volume for the file in the `docker-compose.yaml` so the file is maintained. But I think this should work by default by keeping the file in a folder marked as `VOLUME`. Although I'm not sure if `/home/fetchmail` must be marked as volume. This as the pid file is also stored there and that can obviously lead to issues if the container is killed while fetchmail is running.

**Comment by hoellen** [comment] 2019-12-13 16:57
I think this is a duplicate of #1223.

**Comment by RobertMe** [comment] 2019-12-13 17:10
You're right. I searched for `.fetchids` but it didn't show any results. But apparently GitHub doesn't maintain the issues context when starting a search from the issues page on mobile so it searched in code...

(Leaving it open for know so maintainers can close and add proper labels)

**Closed** 2019-12-14 08:10 UTC
