### ISSUE TITLE
Disk running out of space — Clamav fills up tmp directory

### ISSUE THREAD

**Issue by deze333** [Mailu/Mailu#1419] opened 2020-03-25 10:19 UTC
After a few weeks of running, I noticed that the machine was left with 0 free  disk space and webmail stopped working.

It turned out that the directory `/mailu/filter/tmp` was filled with **36Gb** worth of temp subdirs.

```bash
me@mail:/mailu/filter/tmp$ ls
clamav-0018c4535a19139a285faa4214c50140.tmp  clamav-4668d952f865be239b6eaaac306ba65a.tmp  clamav-90cf5d29bbf6909f8d1e1e0ec4334a0c.tmp  clamav-c1b53d9a3671bb3a5eae26b1de3cb858.tmp
clamav-01c82ec5360e5c92fbe5333a44960f48.tmp  clamav-4c21930e870693ba2546412f57a83b8b.tmp  clamav-916db5c82e8edae16f4793dc368ec066.tmp  clamav-c6e99945b8217f608290a34a51d1e1b5.tmp
clamav-036365503c0d16eeaffb7c8412c0aeff.tmp  clamav-4cbca85252a4d0b1823f5c2e304b8e8e.tmp  clamav-916f64c79c047e33685d795526437fb6.tmp  clamav-caf5c0ce146a669133ed14e4195b25fb.tmp
clamav-0fd8bfdfe87628ecc26ad7aeea027815.tmp  clamav-4e66dce56d150d22c80bc2bfe0f33aee.tmp  clamav-92786c21fcc5dd03687962efeef6eadc.tmp  clamav-cbb918cf5dedb74319a9ba57655b1bfb.tmp
clamav-102341556d6f9215d641d47b84256f1c.tmp  clamav-4ee18219c935e0156c61d13c0c5de6a3.tmp  clamav-93718f7086b04d73e0a817d8585bd3d6.tmp  clamav-cdc372fcc5916a8befccfbdabf94b270.tmp
clamav-112134187c5e0c286bc851001af3e39e.tmp  clamav-501d7d8db64c04d2bd1a0ab815b9cf31.tmp  clamav-93b5c4ba88d7dce437b2271dcb2714e5.tmp  clamav-d0ef6c2dd7aa16f30a66bff2b714a2d0.tmp
clamav-13e3c7f035a0322aeb1a9f6acd983ab1.tmp  clamav-50f6540949448b56d8b4113ea5cfa327.tmp  clamav-96aa14b4b0b38ce9f8c4fac80d91bfcb.tmp  clamav-d33dcabe7fe7fb03d8a50a3139c56c71.tmp
clamav-176101b1f3209f6e71563ae33d1788d5.tmp  clamav-521500d88d48c114bf52c3db431d5c81.tmp  clamav-99c840e751ec3dc026490c7448b712e4.tmp  clamav-d65583c4fdfa80761f792a9593fc178b.tmp
clamav-1b03227a8cfcef96f10cbc655158a156.tmp  clamav-52ba0665fa77cdb48ef4d35c37ef879f.tmp  clamav-9d4f48846bbf604acd91c43dc0f2605d.tmp  clamav-d73e7e9c0923971c7bebf6de9f43657d.tmp
clamav-1cba99f77e77d6b4ace0a1874ba7e235.tmp  clamav-54a8674557ba1ae42eb4aa28f754f27b.tmp  clamav-9de0ff3f379b1b74f2e5cf8c49b0b8fc.tmp  clamav-d9841631b87ed399a78d6741322f99bc.tmp
clamav-1d4a7499608ee1b50b929ded06582838.tmp  clamav-571f1e52976fc248b427aee983ebe7d9.tmp  clamav-9ea2abdcc7d55a403d00a0cbb33a1ab9.tmp  clamav-dc213157e9ed833e540e01ef366052ec.tmp
clamav-20cee042eba2631c6034d6cb2ff8196a.tmp  clamav-5a063eff433a3de85c27b4bbdd3e682e.tmp  clamav-a51772d1f3467def4f56fa105899f456.tmp  clamav-dd1bd2ae0ec87bca6f723b488502b9c5.tmp
clamav-20e34713cd15a3397b6469ccf593b10c.tmp  clamav-5a0e6bbf86143aeccee6aa7910fa49b7.tmp  clamav-a545fa59ca1fb297a8ff22972bf58317.tmp  clamav-e1b1d3d043cc581834a434ae89b2af55.tmp
clamav-24956547bab82a402021417e395a2702.tmp  clamav-5c275562d2191f236fc9c13afc41f4eb.tmp  clamav-a66c311ef56b2bb00450cc54785a1777.tmp  clamav-e2a17b4c85324d83d1961f558bb604db.tmp
clamav-25b99e72eb34aca80fc0887ffa98531b.tmp  clamav-6084b9bbc19c4bfa1f65c6dcd57167fd.tmp  clamav-a75e390832e331ac32613dcc5f7ab531.tmp  clamav-e4dfbb14305853953239bdaf7d9e50db.tmp
clamav-2734282f468b72669773445a166f7943.tmp  clamav-6284947abd3ea07f0cddf3847d3d1db1.tmp  clamav-a77a2826bd10fc7f23eb8f9e6ff1ba9b.tmp  clamav-eb2d4b2fa313e18753d26e0f293e7ae9.tmp
clamav-294785c0eef086f7038ae972b157d0b0.tmp  clamav-6afa2b9ea875d402271cc7bcfc013340.tmp  clamav-aafcf01bc4a7c3d3c5f8bb714cdbb2f1.tmp  clamav-eb634f3188a1e7df4365e48a53376459.tmp
clamav-2e51a35b89c54a0ea6a0421a719d6d99.tmp  clamav-6b925cb27f24aa988355953b3f1bc114.tmp  clamav-ac3e3c541eb5368af3621ce055227dce.tmp  clamav-ece1ea01a1c887f594c79141c30ce0f8.tmp
clamav-304faae5b01276b71bb9e7ecedda240e.tmp  clamav-7027b6dee3e05ae1917edc16e0601bff.tmp  clamav-ad346007722f0f0aae5a9edc10fcc36a.tmp  clamav-ed6c95eb5a4cf352d2882b6b62677c61.tmp
clamav-316bf1efcb3ac47b49b1d97b3a35f421.tmp  clamav-75334a9d6decede49734d58a58e9fbc6.tmp  clamav-afeda4d4ff1d8c71b758a8aa3bcd7d93.tmp  clamav-f04f78a7dd69d2dc0573c90fd758e6be.tmp
clamav-34bcb1e09d16c714f067b097f0fafb95.tmp  clamav-826a5000281798eabcc2e15a61c96a24.tmp  clamav-b30a73e932895451fac73d4bd55d95cb.tmp  clamav-f0d2c2d54e5f2cc668e2f7b8c6374c80.tmp
clamav-35199def63efdb0c8520a5d8ac060bdc.tmp  clamav-84b07a9d96fb6a74434988e0e723650e.tmp  clamav-b30afad3a5f1ebccef0f78000bd5f829.tmp  clamav-f2a0a8019b251da27cf2f97654c2617d.tmp
clamav-35d785a3023a1183834d365911d6947c.tmp  clamav-875235f54d3dc3f520e779f9814a0c0d.tmp  clamav-b59009d2eabacd48eec127e65967ed70.tmp  clamav-f351e37539bbf1602a4117d59f360c73.tmp
clamav-363db57ed83de00ef700328132531d62.tmp  clamav-8885753e1095e76014124c519f8cb157.tmp  clamav-b827253b3a47ca780abb43be71039fcd.tmp  clamav-f55b269c42691c1fabc472d7cc464407.tmp
clamav-3945ad714b8b0d5227e21972f9057ace.tmp  clamav-89d5ea34dc4712ac93cbd6c767af965f.tmp  clamav-bdbccd8495e451b14127b7d68ed6ac25.tmp  clamav-fa50921986c8daac63eb70dec5457c59.tmp
clamav-3b7eca1870fb08773e38ceb82293f543.tmp  clamav-8be97c6c0b42d7ec42b29ad5a6ab3a34.tmp  clamav-bf64c7bc94a36dcd05b8980fb2cd3e33.tmp  clamav-fbdc74ef0959ff74047adef42ba04b8d.tmp
clamav-4439fbd988e8a8ca88243060201e8f28.tmp  clamav-9003f8c918300f862eed6781b94f1cf7.tmp  clamav-c0e045433c05da5420d4a5deaf92d7c6.tmp
```

**Comment by te-online** [comment] 2020-03-26 14:50
I experienced the same thing, but I believe this was related to the fact that the instance was overwhelmed in general. I misconfigured `iptables` so the instance was acting as an open relay for a few hours. That filled up the `filter/tmp` directory and resource usage in general spiked *(looking at you, dear spammers)*.

So, not really a solution, but just a thing to check: Did you make sure you have enough resources for all containers to run smoothly and you're not exposing an open relay? 

Another solution could be running a cronjob with something like `find /mailu/filter/tmp/clamav-* -mtime +14 -exec rm -rf {} \;`. **Careful**: I don't know if this leads to inconsistencies, since I haven't read clamav's manual on temp data. That said, it'd be a bit careless to save important data in a directory called `tmp` that has to be expected to be cleared.

**Comment by te-online** [comment] 2020-03-27 18:15
I have to add that some aspects of my previous answer were wrong:
- Apparently the problem still persists. Although resources are now back to normal, the antivirus container fills up the disk
- The path in my example command was wrong
- I still can't say if deleting the `.tmp` files will do harm, but until we figure out what's wrong, this is my only solution.

**Comment by deze333** [comment] 2020-03-28 03:17
Thank you for sharing ideas, very helpful. Strangely enough last few days didn't produce any additional temp files. Looks like that this situation only happens under certain circumstances. Will keep monitoring and report if any updates!

**Comment by te-online** [comment] 2020-04-10 17:28
Happened again to me today. 29 Gigabyte worth of filter *.tmp folders... All of them created or modified today, so my script failed to delete old temp files, because ... well, they weren't old. I'm wondering why this is happening 🤔

**Comment by HorayNarea** [comment] 2020-04-12 22:37
If your server is running out of RAM then ClamAV gets killed which is usually the reason for old files in the clamav volume… if you have less than 4 GB of RAM you should not enable ClamAV

**Comment by te-online** [comment] 2020-04-14 16:14
Thanks for this helpful hint. Since the manual stated that 2 GB were the minimum, I chose only 2 GB of RAM. That clamav might need more resources and might crash sounds reasonable. Couldn't see anything related in the logs, though. The server isn't exactly at it's limit, but it's pretty busy all the time with some peaks then and again, so probably a good indicator that more resources are needed. I'll try ramping up the RAM to 4 GB for a while and see what happens!

**Comment by muhlemmer** [comment] 2020-05-02 11:34
This is a duplicate of #470 and continues to be an issue...

**Comment by muhlemmer** [comment] 2020-05-03 20:48
Further discussion will be held in #470 and #1482. This will now be closed.

**Closed by muhlemmer** 2020-05-03 20:48 UTC
