### ISSUE TITLE
Connection to storage server failed.

### ISSUE THREAD

**Issue by TheOtherRealm** [Mailu/Mailu#1171] opened 2019-09-16 18:45 UTC
I am trying to get the login system for round to work.  I finally got the system up and can login to the admin interface ( https://mail.example.org/admin/ ) but when I click on the webmail link and try to log in, after about a minute of "Sending…" I get "Connection to storage server failed."  However, if I try the wrong password, I get "Login Failed" so it clearly can communicate with some part of the server, just not the storage server, otherwise it would give the same message regardless of what I put in.
Here is the log I when I try to log in:

```
webmail_1    | 127.0.0.1 - - [16/Sep/2019:18:00:33 +0000] "GET / HTTP/1.1" 200 6141 "-" "curl/7.64.0"
front_1      | 2019/09/16 18:00:41 [info] 15#15: *500 upstream sent invalid response: "* OK Waiting for authentication process to respond.." while reading response from upstream, client: 192.168.203.12, server: 0.0.0.0:10143, login: "admin@theotherrealm.org", upstream: 192.168.203.6:143
imap_1       | Sep 16 18:00:41 auth-worker(1086): Warning: Dict server timeout: No input since connected 30.027 secs ago (1 commands pending, oldest sent 30.027 secs ago: Lshared/passdb/admin@theotherrealm.org, 30.028 in dict wait, 0.000 in other ioloops, 0.000 in locks) - reconnected
imap_1       | ERROR:asyncio:_GatheringFuture exception was never retrieved
imap_1       | future: <_GatheringFuture finished exception=ClientConnectorError(111, "Connect call failed ('192.168.203.9', 80)")>
imap_1       | Traceback (most recent call last):
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 929, in _wrap_create_connection
imap_1       |     await self._loop.create_connection(*args, **kwargs))
imap_1       |   File "/usr/lib/python3.7/asyncio/base_events.py", line 959, in create_connection
imap_1       |     raise exceptions[0]
imap_1       |   File "/usr/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
imap_1       |     await self.sock_connect(sock, address)
imap_1       |   File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
imap_1       |     return await fut
imap_1       |   File "/usr/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
imap_1       |     raise OSError(err, f'Connect call failed {address}')
imap_1       | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.203.9', 80)
imap_1       | 
imap_1       | The above exception was the direct cause of the following exception:
imap_1       | 
imap_1       | Traceback (most recent call last):
imap_1       |   File "/usr/lib/python3.7/site-packages/podop/dovecot.py", line 86, in process_lookup
imap_1       |     key, ns=(self.user if key_type == "priv" else None)
imap_1       |   File "/usr/lib/python3.7/site-packages/podop/table.py", line 27, in get
imap_1       |     async with session.get(self.url_pattern.format(quoted_key)) as request:
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 1013, in __aenter__
imap_1       |     self._resp = await self._coro
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 484, in _request
imap_1       |     timeout=real_timeout
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
imap_1       |     proto = await self._create_connection(req, traces, timeout)
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
imap_1       |     req, traces, timeout)
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 997, in _create_direct_connection
imap_1       |     raise last_exc
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 979, in _create_direct_connection
imap_1       |     req=req, client_error=client_error)
imap_1       |   File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
imap_1       |     raise client_error(req.connection_key, exc) from exc
imap_1       | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.203.9:80 ssl:None [Connect call failed ('192.168.203.9', 80)]
webmail_1    | 192.168.203.3 - - [16/Sep/2019:18:00:10 +0000] "POST /?_task=login HTTP/1.1" 200 2971 "https://mail.theotherrealm.org/webmail/?_task=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
front_1      | 174.83.38.187 - - [16/Sep/2019:18:00:42 +0000] "POST /webmail/?_task=login HTTP/2.0" 200 2223 "https://mail.theotherrealm.org/webmail/?_task=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0")

```
This leads me to think it should be connecting on port 443 but it's doing it on 80 ( `imap_1       | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.203.9:80 ssl:None [Connect call failed ('192.168.203.9', 80)]` ).  Let's Encrypt seems to be working though, so it mush just be in the docker container.  Either that or it is something completely different - I have only been working with Mailu for a couple of days.

Here is my .env file, minus the passwords and such
```

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=1234567890

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=example.org

# Hostnames for this server, separated with comas
HOSTNAMES=mail.example.org

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour 

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=roundcube

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=gz
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Website name
SITENAME=Test

# Linked Website URL
WEBSITE=https://example.org



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=BLF-CRYPT

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=postgresql
DB_PW=1234567890
```

**Comment by kaiyou** [comment] 2019-09-18 06:12
No, internal connection from the IMAP and SMTP container to the admin container use http over port 80, so that is not the issue.

I fear you are facing one of the errors due to resolving. Could you docker inspect the amin container and check that the address in the error message is that of the amin container? If not, simply restarting the IMAP and SMTP container should do.

**Comment by TheOtherRealm** [comment] 2019-09-18 15:28
So I switched to RainLoop and everything works.  Not sure what the issue is with RoundCube but I because I actually like the UI of RainLoop better, I am not going to keep debugging this.  It seems to be a bug though so I won't close this issue.  It could have something to do with the fact that I couldn't get the ports to work using the full unique IP in the docker-compose.yml file.  If that's the case though, I don't know why RainLoop and the Admin parts work.

**Comment by kaiyou** [comment] 2019-09-18 17:43
I will conduct some tests tonight. I fear that switching webmail also had the effect to resolve a temporary resolution issue. Would you be so kind as to test once more with Rainloop to confirm if this is reproducible?

**Comment by TheOtherRealm** [comment] 2019-09-18 19:27
The problem persists.  I switched back to roundcube and was still not able to log in, giving the same connection storage issue.  Switched back to Rainloop and all was well.  I think it is something with an inability to connect to the PostgreSQL database.

**Comment by kaiyou** [comment] 2019-09-19 05:50
There should not be any posgres database. Thanks for that confirmation though. We will investigate further from here.

**Comment by Get-Smart1** [comment] 2019-11-18 21:37
Any update on this? I facing the same issue but with sqllite :/

**Comment by micw** [comment] 2019-11-19 05:18
Seems unrelated to the database, (our) dovecot does not support others than sqlite yet and the error says that it cannot connect to imap.
@Get-Smart1 What exact error do you see?

**Comment by Nebukadneza** [comment] 2020-08-17 19:09
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by macdabby** [comment] 2020-09-05 13:10
I'm not sure if this is related but i had the same error message. in my case this was a newly created account and the path for the email address did not exist in the /mail path. when i created that manually, then logging in work. this might not be the same issue since i was also not able to send mail TO that account, but it looks like the OP might have been able to.

**Comment by Diman0** [comment] 2020-09-25 11:41
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Closed by Diman0** 2020-09-25 11:41 UTC

**Comment by flavienbwk** [comment] 2020-10-14 15:22
Issue still exist.

**Comment by kevinveenbirkenbach** [comment] 2021-08-23 06:17
The issue is not solved. Please don't close open issues which are bugs. I understand that you have man power problems but closing issues which aren't fixed doesn't help at all.

**Comment by ghostwheel42** [comment] 2021-08-23 12:26
@flavienbwk @kevinveenbirkenbach Hi. This is a really old issue for an old version of mailu.
I can't reproduce the roundcube error "Connection to storage server failed.".
If you can provide more information on how to reproduce this, please open a new issue for the current Mailu version 1.8.

**Comment by macdabby** [comment] 2021-08-23 12:59
Hey just looking at this - 192.168.203.9 is timing out on port 80. why is the imap container trying to connect to anything on port 80? and why is that address there? that doesn't seem to be a docker address (unless you set them manually) - is that your local IP address? is it correct? if you run `docker ps` does it show that there is a container with port 80 open on your local machine? can you access it with `curl 192.168.203.9:80` ?

if this is supposed to be one container talking to another, the IP should look like 172.17.x.x , unless you manually changed that.

**Comment by ghostwheel42** [comment] 2021-08-23 15:02
@macdabby the setup-tool for mailu sets the 192.168.x.y IPs in the compose file. the communication to the admin container port 80 is okay.
