### ISSUE TITLE
Proper way to add custom sieve scripts?

### ISSUE THREAD

**Issue by jkaberg** [Mailu/Mailu#467] opened 2018-04-30 10:48 UTC
Is there one? For instance, I couldn't find any functionality to sort tagged mails into folder so I created a sieve script to do it:

```
require"fileinto";
require"mailbox";
require"variables";
require"subaddress";
require"envelope";

ifallof (
  envelope :detail :matches "to" "*"
  ) {
  set :lower :upperfirst "tag" " ${1}";

  if mailbox exists "${1}" {
    fileinto "${1}";
  } else {
    fileinto :create "${tag}";
  }
}
```

But I'm failing to find the proper way to do so. If there is none, consider this a request 😄 

Currently I'm mounting this ontop of /var/lib/dovecot/after.sieve in the imap container

**Comment by kaiyou** [comment] 2018-05-28 20:46
Sorry about the terrible delay. Unfortunately there is not currently, but I guess it could be added as part of overrides. The general idea is to be able to edit sieve scripts in the admin interface in the end.

**Comment by hoellen** [comment] 2018-07-09 10:40
This could be a workaround for you: 
If you use the build in webmail (e.g. rainloop). You can set in the admin panel of rainloop the following sieve settings: 
```
Server:   mailu_imap_1
Port:     4190
Security: none
```
So every user can use sieve scripts in the webmailer. This works at least for me.

**Comment by kaiyou** [comment] 2018-09-28 09:35
Closing as a duplicate of #497, will merge the discussion there

**Closed by kaiyou** 2018-09-28 09:35 UTC
Labels: feature
