### ISSUE TITLE
Not fetching some mail

### ISSUE THREAD

**Issue by rwdj** [Mailu/Mailu#1498] opened 2020-05-09 23:20 UTC
I have a domain MX'd to send email to a more reliable gmail account. Mailu uses IMAP to fetch the emails from the gmail account to my account on Mailu.

Most emails make it, like those from AWS, but some don't, like github's "new email added"/"verify your email" emails. 

I've gone so far as removing the Antispam filter with `ANTISPAM=none` and removing the antispam container. Before and after, I can't get the github email, among others. 

```
b'46 messages (44 seen) for xxx@gmail.com at imap.gmail.com.\nreading message xxx@gmail.com@imap.gmail.com:13 of 46 (6532 header octets) not flushed\nreading message xxx@gmail.com@imap.gmail.com:14 of 46 (5192 header octets) not flushed\n'
```

fetchmail shows the new emails when fetching, but isn't adding them to my inbox.

What steps should I take? I haven't done anything special to the containers' internal configuration. I've only edited the mailu.env file.

What additional information would be helpful?

MAILU: 1.7
DATABASE: Postgresql 12

**Comment by rwdj** [comment] 2020-05-10 02:43
Changed to POP3 with the same result except nothing is coming through, now.

A message of interest might be:
```
smtp_1       | May 10 02:35:01 rwdj postfix/smtpd[185]: NOQUEUE: milter-reject: MAIL from rwdjmail_fetchmail_1.rwdjmail_external[192.168.203.2]: 451 4.7.1 Service unavailable - try again later; from=<bounces+274508-7d84-xxx=gmail.com@sendgrid.net> proto=ESMTP helo=<f9ed10764806>
```
This looks like a rate limit, but my inexperience makes me hesitate, since fetchmail is reaching it fine.

**Comment by ofthesun9** [comment] 2020-05-10 07:46
Hello,
You need to keep the antispam service. It is not an optional service ;-) You have an option in the admin panel to enable/disable/adjust  it per user.

Regarding your first issue (github), is it possible that gmail is storing those emails in a specific folder, whereas fetchmail would only retrieve mail from the main inbox ?

**Comment by rwdj** [comment] 2020-05-10 16:07
Thank you. Added it back and that fixed a new problem I was having combined with a network issue. But, the original problem persists. 

No, sadly. The inbox is the only folder I'm looking at. I'm watching emails arrive in my inbox such as the github "verify email", paypal receipt and personal external-account emails. The paypal receipt and my personal emails arrived fine. The github emails did not.

However, after a lot of work and cleanup, I see this.

```
smtp_1       | May 10 15:52:58 rwdj postfix/cleanup[289]: 4FEA65801E5: milter-reject: END-OF-MESSAGE from mail_fetchmail_1.mail_default[192.168.203.4]: 5.7.1 Spam message rejected; from=<noreply@github.com> to=<xxx@rwdjmailu.com> proto=ESMTP helo=<765fdc99f115>
fetchmail_1  | fetchmail: SMTP listener refused delivery
```

The account has antispam turned off, but it seems to be bouncing before it even reaches the account. Actually, I want to allow spam. I have another way to handle this. I've tried with and without `ANTISPAM=none`, but I get the same result.

**Comment by ofthesun9** [comment] 2020-05-11 08:56
Sounds like a duplicate of #1231

**Comment by rwdj** [comment] 2020-05-11 12:16
That it might be. 
But, how can I just disable all spam rules. Editing the rules would be nice, which I assume is what #1231 is asking? It doesn’t really say what it wants. 
Anyways, I want to completely disable it. Accept all spam. No fetched message left behind.

**Closed** 2020-05-11 12:24 UTC
