### ISSUE TITLE
Refactor the way our containers communicate

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#1013] opened 2019-05-07 08:07 UTC
Now that the admin container is using mailustart, it does all kinds of DNS resolving at startup. I believe this is wrong, since it does not account for any container changing IP during the life of the admin container, and we know this happens. A lot.

Currently the admin container take a couple minutes to start in a dev environment since not all hosts exist and resolve. Also, once an IP changes, all things break. Also, this basically prevents any scaling and load balancing (even though I agree it is an edge case for Mailu).

I would rather have a simple wrapper for live resolving that supports retrying and caching, and do live resolving on the fly.

**Comment by kaiyou** [comment] 2019-05-07 08:13
I am starting to think something a lot more radical needs be done. The admin container is fine since resolving can be performed live, but nginx and Postfix do not support this for instance. Many ideas, I'll dig some of them, including live config reloading and proxying.

**Comment by kaiyou** [comment] 2019-05-07 08:34
After some thought, I  renamed the issue to be more general because I think we need to think fresh and avoid any old preconceived idea.

Basically, most container environments rely on either DNS or distributed configuration for resolving the addresses of other containers. We need to support these. I would says we start with DNS (what we have been doing so far) and slowly build upon it.

Now, how should we reconcile dynamically resolving another containers address and services that do not provide live address resolution? I believe we have a couple possibilities :

- hacking the software in question (nginx -- which we already did :smile: , Postfix -- which we mostly already did in Podop) to use only live queries;
- switch to software that support live queries or stop relying on them  altogether (hard, I believe);
- reload the configuration at runtime when the destination of a query should change.

I am thinking a lot about these options, and will be reviewing where exactly we use address resolution and what the alternatives are in each case, reporting here.

**Comment by kaiyou** [comment] 2019-05-07 08:47
Here are the places containers currently reference each other : 
 - the admin container provides references to nginx and podop for various use cases, it is inside the API so perfectly able to do live querying
 - nginx has references to the admin, antispam, webdav and webmail, it is nginx so we know how to hack si it does live DNS querying
 - Postfix has references to imap and antispam, those are static; they could probably replaced with podop calls
 - Fetchmail has a reference to the smtp call, but it is able to do live resolution
- Rspamd does live resolution already.

So it is conceivable to keep going with DNS. What we need though is to get back to live resolution for all these addresses. I can work on using Podop for the remaining ones in Postfix. Then I think we should write a simply retrying wrapper with cache for DNS resolution. And finally I say we move back to dynamic resolution.

**Comment by Nebukadneza** [comment] 2020-08-18 18:32
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by micw** [comment] 2021-01-09 12:45
@kaiyou @Nebukadneza
Please have a look to the PR above. In the helm chart I already use *_ADDRESS without any static DNS resolution. I added the *_ADDRESS stuff long time ago to workaround the issues that static resolution brings and it works properly (at least on kubernetes). Personally I cannot see any reason to stick with the static DNS resolution. If you agree that we can drop it, I give the PR try on my own server and if all works, I'd aprove it for merge.

**Comment by tvelocity** [comment] 2021-01-10 15:21
Hello,

Thank you for your follow up, micw.

While investigating the issue on my setup, and any related commits from the past, I found #886 and #827 for IPv6 support. The issue is the Docker DNS resolution being unreliable on IPv6, which is why the startup resolution was introduced there. I am not aware if there are any other reasons besides IPv6.

It is notable that using startup address resolution to work around DNS problems, is going to bring all the issues caused by the static addresses even on those setups that suffered from the Docker DNS bugs. A container may still eventually be restarted with a different IP. So IMHO it is just trading one problem with another.

Given IPv6 is just badly supported in Docker overall, and that the source of the problem is Docker itself, in my view it is worth it reconsidering whether the issues that come with startup address resolution are a worth it.

That is assuming there are no other reasons behind the startup address resolution.

If on the other hand the startup address resolution really needs to stay, I would suggest not to do it by default. For example, Mailu could by default just copy HOST_\* to \*_ADDRESS variables without resolving them, unless a configuration env variable is set to enable resolution.

**Closed** 2022-12-19 10:38 UTC
Labels: type/enhancement, backlog
