### ISSUE TITLE
Make quota configurable in smaller steps or freetext

### ISSUE THREAD

**Issue by promasu** [Mailu/Mailu#2376] opened 2022-06-12 06:58 UTC
Currently quota is only configurable in full gigabyte steps and not in 100 megabyte steps for example.
Maybe you can consider to make the quota configurable with a freetext field

**Comment by nextgens** [comment] 2022-06-12 09:12
ACK. This is a duplicate of #2242

**Closed by nextgens** 2022-06-12 09:12 UTC
