### ISSUE TITLE
Autoconfiguration support for mail clients (daboo, srv, thunderbird)

### ISSUE THREAD

**Issue by Thorsten1976** [Mailu/Mailu#498] opened 2018-06-14 06:32 UTC
- https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration
- https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo
- https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat
- https://tools.ietf.org/html/draft-daboo-srv-email-02

**Comment by hoellen** [comment] 2018-06-14 21:05
Duplicate of #224

**Comment by mmoo9154** [comment] 2018-06-25 16:22
What is the benefit of adding autoconfiguration?  According to the Mozilla specification:

> Thunderbird tries to guess the configuration, by trying common server names like imap.<domain>, smtp.<domain>, mail.<domain> etc., and, when a mail server answers, checking whether it supports SSL, STARTTLS and encrypted passwords (CRAM-MD5).

If DNS entries are made for imap.example.com & smtp.example.com, or for mail.example.com and there is a valid imap/smtp server at the IP, every major mail platform will autoconfigure.

It seems if there maybe no need for a change.

It might be nice to add a "validate DNS settings" capability.  This could validate the MX, SPF, DKIM, and DMARC entries as well as IMAP and SMTP and simply flag any missing or incorrect entries.

**Comment by HorayNarea** [comment] 2018-06-26 17:43
The benefit is that autoconfig works with more than just Thunderbird and it's a documented features, not just "well somehow that works"
(also: "Thunderbird is smart and guesses the right server names" is a blatant lie, my mailserver is on mail.domain.tld since many years and Thunderbird never guessed mail.domain.tld as the IMAP/SMTP server :D)

**Comment by kaiyou** [comment] 2018-09-28 09:33
This is a duplicate of #224, closing this issue and referencing it

**Closed by kaiyou** 2018-09-28 09:33 UTC
