### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mikelopez654** [Mailu/Mailu#1565] opened 2020-07-09 11:18 UTC
When using the web setup, upon submission of the form I get the following error....Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Been going on for several hours now.  I've used the form successfully before so I know it works, so something's up.

**Comment by OscarPaz** [comment] 2020-07-09 20:18
Duplicate of #1527.

**Comment by OscarPaz** [comment] 2020-07-09 20:21
@mikelopez654: check out #1563.

**Comment by mikelopez654** [comment] 2020-07-10 07:35
@OscarPaz Thank you, Oscar!

**Closed** 2020-07-10 07:36 UTC
