### ISSUE TITLE
Make reject_authenticated_sender_login_mismatch configurable

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1163] opened 2019-09-05 20:04 UTC
In postfix master.cf, reject_authenticated_sender_login_mismatch is always enabled. This ensures that if a user is authenticated, he can only use the authentication mail address as sender.

There are situations where this is not wanted:
- clients that have multiple mail aliases configured for one account
- other MTAs that use mailu as upstream smarthost with smtp authentication

The options should have a high-level name like "ALLOW_ANY_FROM_ADDRESS_FOR_AUTHENTICATED_SENDER"

**Comment by micw** [comment] 2019-09-05 20:04
cc @benbucksch

**Comment by benbucksch** [comment] 2019-09-05 20:26
I think this config option should be higher level, e.g. `allow_any_from_address=yes`. It should then be mapped to Postfix options as needed.

**Comment by Nebukadneza** [comment] 2020-08-15 21:25
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by benbucksch** [comment] 2020-08-15 22:53
This bug is actively preventing me from sending email, because mailu rejects my email address.

This is by far the worst mailu bug for me and complete stopper.

I cannot post the emojis due to vacation (2FA). Could somebody please do a thumb on my behalf?
-- 
Sent from my cell phone. Please excuse the brevity.

**Comment by benbucksch** [comment] 2020-09-24 01:39
This is causing me great problems and preventing me from sending emails (when using mailu as mail server).

**Comment by xamanu** [comment] 2020-09-25 18:48
I have a catch-all domain for the multiple accounts one has to do everywhere. This allows me to prevent spam, know who passes on email addresses and allows me to block them one by one.

Sending emails from one account on behalf of any of the catch-all domains is an essential feature for me. It worked well with previous versions of Mailu and I'm looking forward to getting it hopefully back in the future. Thanks!

**Comment by nextgens** [comment] 2021-08-02 14:03
This is a duplicate of #1096

**Closed by nextgens** 2021-08-02 14:03 UTC
Labels: backlog
