### ISSUE TITLE
admin binds port 80 and that is problematic on some platforms

### ISSUE THREAD

**Issue by Pompiedom** [Mailu/Mailu#2906] opened 2023-08-13 22:07 UTC
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

```
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
```

## Description
I'm trying to get mailu to work on synology docker. It's the furthest I've ever come to get mailu to work. The mailu_admin logs the underneath issue. I see port 80 is referenced but in my yml I used other ports (as 80 and 443 are prohibited). Shouldn't this port be updated following the yml?

```
WARNING:root:Disabling hardened-malloc on this CPU
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-08-13 23:33:07 +0200] [18] [INFO] Starting gunicorn 20.1.0
[2023-08-13 23:33:07 +0200] [18] [ERROR] Retrying in 1 second.
[2023-08-13 23:33:08 +0200] [18] [ERROR] Retrying in 1 second.
[2023-08-13 23:33:09 +0200] [18] [ERROR] Retrying in 1 second.
[2023-08-13 23:33:10 +0200] [18] [ERROR] Retrying in 1 second.
[2023-08-13 23:33:11 +0200] [18] [ERROR] Retrying in 1 second.
[2023-08-13 23:33:12 +0200] [18] [ERROR] Can't connect to ('', 80)
```
## YML
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/volume1/docker/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "0.0.0.0:980:80"
      - "0.0.0.0:9443:443"
      - "0.0.0.0:925:25"
      - "0.0.0.0:9465:465"
      - "0.0.0.0:9587:587"
      - "0.0.0.0:9110:110"
      - "0.0.0.0:9995:995"
      - "0.0.0.0:9143:143"
      - "0.0.0.0:9993:993"
    networks:
      - default
      - webmail
    volumes:
      - "/volume1/docker/mailu/certs:/certs"
      - "/volume1/docker/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/volume1/docker/mailu/data:/data"
      - "/volume1/docker/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/volume1/docker/mailu/mail:/mail"
      - "/volume1/docker/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/volume1/docker/mailu/mailqueue:/queue"
      - "/volume1/docker/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254


  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    volumes:
      - "/volume1/docker/mailu/filter:/var/lib/rspamd"
      - "/volume1/docker/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/volume1/docker/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254


  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/volume1/docker/mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/volume1/docker/mailu/webmail:/data"
      - "/volume1/docker/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge

```

## Env

```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=xxx

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=x.nl

# Hostnames for this server, separated with comas
HOSTNAMES=mail.x.nl

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=5/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none)
WEBMAIL=roundcube

# Expose the API interface (value: true, false)
API=false

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

# Scan Macros solution (value: true, false)
SCAN_MACROS=false

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=true

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=gz
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Path to the API interface if enabled
WEB_API=

# Website name
SITENAME=x

# Linked Website URL
WEBSITE=https://x.nl



###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Europe/Amsterdam

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=80

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=

```

**Comment by nextgens** [comment] 2023-08-14 07:14
Internally port 80 is used to "talk" to the admin container, this is why it fails. We could change it... can you tell us more about the target platform and why port 80 is unusable? In Mailu's case, it only attempts to bind it on the IP address assigned to the docker container of "admin"... which should not be prohibited/cause interferences.

**Comment by Pompiedom** [comment] 2023-08-14 09:12
I run everything on synology (latest DSM) docker.

Port 80 is being used (or in use) as many services and dockers are being ran.

What about the empty "" before the port 80?

**Comment by Pompiedom** [comment] 2023-08-14 10:05
What can I do/post to help analyze this issue?

**Comment by ghostwheel42** [comment] 2023-08-14 10:18
> I don't understand why you get `'':80`, I would expect just `:80`

This is only the python tuple of (host, port) - but maybe we could explicitely use "0.0.0.0" in `start.py` when binding:
```
    # If SUBNET6 is defined, gunicorn must listen on IPv6 as well as IPv4
    "-b", f"{'[::]' if os.environ.get('SUBNET6') else '0.0.0.0'}:80",
```

**Comment by Pompiedom** [comment] 2023-08-15 22:15
```
docker-compose exec admin busybox nc -lp 80
GET /internal/rspamd/local_domains HTTP/1.1
Host: admin
User-Agent: python-requests/2.31.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive

ERROR: 137
```

And the second one doesn't respond back, it also doesn't time-out. It just "hangs".

**Comment by nextgens** [comment] 2023-08-16 07:32
So this is working as intended, showcasing that port 80 can be bound.

``
# docker-compose exec admin
admin# vi /start.py
... edit as suggested by @ghostwheel42 above
admin# /start.py
``

Does the server start then or do you see the same message?

**Comment by Pompiedom** [comment] 2023-08-16 08:17
> So this is working as intended, showcasing that port 80 can be bound.
> 
> ```
> # docker-compose exec admin
> admin# vi /start.py
> ... edit as suggested by @ghostwheel42 above
> admin# /start.py
> ```
> 
> Does the server start then or do you see the same message?

It generates the same message:

`[2023-08-16 08:30:56 +0200] [17] [ERROR] Can't connect to ('', 80)`

**Comment by nextgens** [comment] 2023-08-16 08:22
Even with the edits suggested in https://github.com/Mailu/Mailu/issues/2906#issuecomment-1677060673 ?

It should say something about 0.0.0.0

**Comment by lowne** [comment] 2023-08-28 00:26
Same issue on `podman` rootful (v3.4.4).

> `docker compose exec admin busybox nc -lp 80`

This works just fine because `root` in the container can bind port 80 no problem. `start.py` seemingly drops to user `mailu`, and for some reason the set_cap on gunicorn (on base `Dockerfile`) doesn't stick. 

At any rate I "fixed" the issue (don't have the full stack running yet so YMMV) by hardcoding to port `8080` (in `start.py`) and setting env `ADMIN_ADDRESS=admin:8080` - using a privileged port in a backend container has no benefit AFAIK, so it seems that setting gunicorn on :8080 (and amending `$admin` with the port in `nginx.conf`, like for the other containers) seems the obvious solution.

**Comment by nextgens** [comment] 2023-08-28 09:26
@lowne thank you for the feedback. I would love to understand what has changed and why it doesn't work anymore... but I agree with you that the simplest is probably not to rely on capabilities any-more.

IMHO this is just kicking the can down the road though as we will need them if we want to achieve "rootless" or proper podman support (see #1447)

**Closed** 2023-08-29 06:34 UTC
Labels: priority/p2, type/enhancement
